// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package ds_srv_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errex if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelectMessageRequest struct {
	MessageType          string   `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	UserType             int32    `protobuf:"varint,2,opt,name=UserType,proto3" json:"UserType,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum              int32    `protobuf:"varint,5,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectMessageRequest) Reset()         { *m = SelectMessageRequest{} }
func (m *SelectMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SelectMessageRequest) ProtoMessage()    {}
func (*SelectMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SelectMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectMessageRequest.Unmarshal(m, b)
}
func (m *SelectMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectMessageRequest.Marshal(b, m, deterministic)
}
func (m *SelectMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectMessageRequest.Merge(m, src)
}
func (m *SelectMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SelectMessageRequest.Size(m)
}
func (m *SelectMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectMessageRequest proto.InternalMessageInfo

func (m *SelectMessageRequest) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *SelectMessageRequest) GetUserType() int32 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func (m *SelectMessageRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SelectMessageRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SelectMessageRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type Response struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type IdRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type IdResponse struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResponse) Reset()         { *m = IdResponse{} }
func (m *IdResponse) String() string { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()    {}
func (*IdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *IdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResponse.Unmarshal(m, b)
}
func (m *IdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResponse.Marshal(b, m, deterministic)
}
func (m *IdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResponse.Merge(m, src)
}
func (m *IdResponse) XXX_Size() int {
	return xxx_messageInfo_IdResponse.Size(m)
}
func (m *IdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdResponse proto.InternalMessageInfo

func (m *IdResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type MessageRespone struct {
	Results              string   `protobuf:"bytes,1,opt,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRespone) Reset()         { *m = MessageRespone{} }
func (m *MessageRespone) String() string { return proto.CompactTextString(m) }
func (*MessageRespone) ProtoMessage()    {}
func (*MessageRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *MessageRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRespone.Unmarshal(m, b)
}
func (m *MessageRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRespone.Marshal(b, m, deterministic)
}
func (m *MessageRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRespone.Merge(m, src)
}
func (m *MessageRespone) XXX_Size() int {
	return xxx_messageInfo_MessageRespone.Size(m)
}
func (m *MessageRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRespone.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRespone proto.InternalMessageInfo

func (m *MessageRespone) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

type UpdatMessageContentRequest struct {
	MessageID            int64    `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Picture              string   `protobuf:"bytes,3,opt,name=Picture,proto3" json:"Picture,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	URL                  string   `protobuf:"bytes,5,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatMessageContentRequest) Reset()         { *m = UpdatMessageContentRequest{} }
func (m *UpdatMessageContentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatMessageContentRequest) ProtoMessage()    {}
func (*UpdatMessageContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *UpdatMessageContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatMessageContentRequest.Unmarshal(m, b)
}
func (m *UpdatMessageContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatMessageContentRequest.Marshal(b, m, deterministic)
}
func (m *UpdatMessageContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatMessageContentRequest.Merge(m, src)
}
func (m *UpdatMessageContentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatMessageContentRequest.Size(m)
}
func (m *UpdatMessageContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatMessageContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatMessageContentRequest proto.InternalMessageInfo

func (m *UpdatMessageContentRequest) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *UpdatMessageContentRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatMessageContentRequest) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *UpdatMessageContentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatMessageContentRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type CreatAdRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	MessageType          int64    `protobuf:"varint,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatAdRequest) Reset()         { *m = CreatAdRequest{} }
func (m *CreatAdRequest) String() string { return proto.CompactTextString(m) }
func (*CreatAdRequest) ProtoMessage()    {}
func (*CreatAdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *CreatAdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatAdRequest.Unmarshal(m, b)
}
func (m *CreatAdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatAdRequest.Marshal(b, m, deterministic)
}
func (m *CreatAdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatAdRequest.Merge(m, src)
}
func (m *CreatAdRequest) XXX_Size() int {
	return xxx_messageInfo_CreatAdRequest.Size(m)
}
func (m *CreatAdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatAdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatAdRequest proto.InternalMessageInfo

func (m *CreatAdRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatAdRequest) GetMessageType() int64 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

type UrlRequest struct {
	MessageID            int64    `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlRequest) Reset()         { *m = UrlRequest{} }
func (m *UrlRequest) String() string { return proto.CompactTextString(m) }
func (*UrlRequest) ProtoMessage()    {}
func (*UrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *UrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlRequest.Unmarshal(m, b)
}
func (m *UrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlRequest.Marshal(b, m, deterministic)
}
func (m *UrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlRequest.Merge(m, src)
}
func (m *UrlRequest) XXX_Size() int {
	return xxx_messageInfo_UrlRequest.Size(m)
}
func (m *UrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UrlRequest proto.InternalMessageInfo

func (m *UrlRequest) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *UrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type SelectBannerRequest struct {
	BannerType           int32    `protobuf:"varint,2,opt,name=BannerType,proto3" json:"BannerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectBannerRequest) Reset()         { *m = SelectBannerRequest{} }
func (m *SelectBannerRequest) String() string { return proto.CompactTextString(m) }
func (*SelectBannerRequest) ProtoMessage()    {}
func (*SelectBannerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *SelectBannerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectBannerRequest.Unmarshal(m, b)
}
func (m *SelectBannerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectBannerRequest.Marshal(b, m, deterministic)
}
func (m *SelectBannerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectBannerRequest.Merge(m, src)
}
func (m *SelectBannerRequest) XXX_Size() int {
	return xxx_messageInfo_SelectBannerRequest.Size(m)
}
func (m *SelectBannerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectBannerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectBannerRequest proto.InternalMessageInfo

func (m *SelectBannerRequest) GetBannerType() int32 {
	if m != nil {
		return m.BannerType
	}
	return 0
}

func init() {
	proto.RegisterType((*SelectMessageRequest)(nil), "ds.srv.message.selectMessageRequest")
	proto.RegisterType((*Response)(nil), "ds.srv.message.response")
	proto.RegisterType((*CreateRequest)(nil), "ds.srv.message.createRequest")
	proto.RegisterType((*IdRequest)(nil), "ds.srv.message.idRequest")
	proto.RegisterType((*IdResponse)(nil), "ds.srv.message.idResponse")
	proto.RegisterType((*MessageRespone)(nil), "ds.srv.message.MessageRespone")
	proto.RegisterType((*UpdatMessageContentRequest)(nil), "ds.srv.message.UpdatMessageContentRequest")
	proto.RegisterType((*CreatAdRequest)(nil), "ds.srv.message.CreatAdRequest")
	proto.RegisterType((*UrlRequest)(nil), "ds.srv.message.urlRequest")
	proto.RegisterType((*SelectBannerRequest)(nil), "ds.srv.message.selectBannerRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0xf2, 0xd7, 0xd6, 0xf3, 0x25, 0x51, 0xb4, 0x8d, 0x90, 0x09, 0x05, 0x45, 0x5b, 0x2e,
	0x2a, 0x2e, 0x72, 0xc1, 0xcf, 0x1d, 0x37, 0x34, 0x16, 0x51, 0x10, 0x2d, 0x65, 0xd3, 0x3c, 0xc0,
	0x12, 0x8f, 0x8a, 0x25, 0xc7, 0x0e, 0xbb, 0x6b, 0xa4, 0xf2, 0x20, 0x3c, 0x00, 0x4f, 0xc9, 0x25,
	0xda, 0xf5, 0xae, 0x63, 0x9b, 0xc8, 0x42, 0xea, 0xdd, 0xcc, 0x9c, 0x9d, 0xb3, 0x33, 0x67, 0x8f,
	0x0d, 0x83, 0x2d, 0x4a, 0xc9, 0xef, 0x70, 0xb6, 0x13, 0xa9, 0x4a, 0xc9, 0x30, 0x94, 0x33, 0x29,
	0xbe, 0xcf, 0x6c, 0x95, 0xfe, 0x6a, 0xc1, 0x58, 0x62, 0x8c, 0x1b, 0x75, 0x95, 0x57, 0x18, 0x7e,
	0xcb, 0x50, 0x2a, 0x32, 0x85, 0xff, 0x6d, 0xe5, 0xf6, 0x7e, 0x87, 0x7e, 0x6b, 0xda, 0xba, 0xf0,
	0x58, 0xb9, 0x44, 0x26, 0x70, 0xb2, 0x96, 0x28, 0x0c, 0xdc, 0x9e, 0xb6, 0x2e, 0x7a, 0xac, 0xc8,
	0xc9, 0x23, 0x38, 0xd2, 0xf1, 0x32, 0xf0, 0x3b, 0xa6, 0xd1, 0x66, 0xba, 0xe7, 0x86, 0xdf, 0xe1,
	0x2a, 0xfa, 0x81, 0x7e, 0x37, 0xef, 0x71, 0x39, 0xf1, 0xe1, 0x58, 0xc7, 0xd7, 0xd9, 0xd6, 0xef,
	0x19, 0xc8, 0xa5, 0xf4, 0x35, 0x9c, 0x08, 0x94, 0xbb, 0x34, 0x91, 0x48, 0x08, 0x74, 0x43, 0xae,
	0xb8, 0x19, 0xa8, 0xcf, 0x4c, 0x4c, 0xc6, 0xd0, 0x9b, 0xa7, 0x59, 0xa2, 0xec, 0x18, 0x79, 0x42,
	0xcf, 0x61, 0xb0, 0x11, 0xc8, 0x55, 0xb1, 0xd2, 0x81, 0x56, 0xfa, 0x04, 0xbc, 0x28, 0x74, 0x07,
	0x86, 0xd0, 0x5e, 0x06, 0x06, 0xee, 0xb0, 0xf6, 0x32, 0xa0, 0x67, 0x00, 0x1a, 0xb4, 0x37, 0xd7,
	0xd1, 0x17, 0x30, 0x2c, 0x34, 0xd3, 0x47, 0xcc, 0x06, 0x0c, 0x65, 0x16, 0x2b, 0x69, 0xf5, 0x72,
	0x29, 0xfd, 0xd9, 0x82, 0xc9, 0x7a, 0x17, 0x72, 0xa7, 0xf2, 0x3c, 0x4d, 0x14, 0x26, 0xca, 0x5d,
	0x7c, 0x06, 0x9e, 0x05, 0x8a, 0x1b, 0xf6, 0x05, 0xbd, 0xde, 0x6d, 0xa4, 0xe2, 0x5c, 0x65, 0x8f,
	0xe5, 0x89, 0x91, 0x2b, 0xda, 0xa8, 0x4c, 0xa0, 0xd5, 0xd8, 0xa5, 0x1a, 0xb1, 0xfc, 0x46, 0x63,
	0x8f, 0xb9, 0x94, 0x8c, 0xa0, 0xb3, 0x66, 0x1f, 0x8d, 0xbc, 0x1e, 0xd3, 0x21, 0x7d, 0x0f, 0xc3,
	0xb9, 0x16, 0xe9, 0x5d, 0x58, 0x52, 0xe9, 0x9a, 0x6f, 0xdd, 0x8b, 0x9b, 0xb8, 0x6e, 0x86, 0xb6,
	0x99, 0xb0, 0x5c, 0xa2, 0x6f, 0x01, 0x32, 0x11, 0xff, 0xdb, 0x3e, 0x23, 0xe8, 0x64, 0x22, 0xb6,
	0xdb, 0xe8, 0x90, 0xbe, 0x81, 0xd3, 0xdc, 0x84, 0x97, 0x3c, 0x49, 0x50, 0x38, 0x9a, 0x67, 0x00,
	0x79, 0xa1, 0xe4, 0xb1, 0x52, 0xe5, 0xe5, 0xef, 0x2e, 0x1c, 0x5b, 0x5a, 0xb2, 0x80, 0xe1, 0x02,
	0x9d, 0xbc, 0x97, 0xf7, 0xcb, 0x80, 0x3c, 0x9e, 0x55, 0xbd, 0x3e, 0x2b, 0x1e, 0x7a, 0xe2, 0xd7,
	0x21, 0x67, 0x2f, 0xfa, 0x1f, 0xb9, 0x82, 0xf1, 0x9e, 0x28, 0x40, 0xc5, 0xa3, 0xf8, 0x21, 0x74,
	0x9f, 0x61, 0xb0, 0x2a, 0x7f, 0x5f, 0xe4, 0x79, 0xfd, 0xf0, 0xa1, 0xcf, 0xaf, 0x91, 0xf2, 0x03,
	0x0c, 0xcc, 0x9b, 0xa1, 0xa3, 0x7c, 0x5a, 0x3f, 0x5c, 0xf1, 0x7d, 0x23, 0xd7, 0x0d, 0x9c, 0x56,
	0xb8, 0xf2, 0x85, 0x1f, 0xc2, 0xb8, 0x80, 0xfe, 0x5e, 0xbf, 0x66, 0xdd, 0x26, 0x87, 0xa0, 0xd2,
	0x9a, 0xa3, 0xca, 0x68, 0x6b, 0x11, 0x93, 0xbf, 0x3a, 0xf6, 0xa6, 0x6b, 0x1c, 0xea, 0x13, 0xf4,
	0x57, 0xc8, 0xc5, 0xe6, 0x6b, 0xee, 0x1e, 0x72, 0x7e, 0xf8, 0x11, 0x2a, 0xf6, 0x6b, 0x22, 0xfc,
	0x72, 0x64, 0x7e, 0xa7, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xf6, 0xfb, 0xb5, 0x5f,
	0x05, 0x00, 0x00,
}
