// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base_ex.proto

package jz_micro_jzback_srv_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonOutput struct {
	HttpCode             int32    `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Detail               string   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonOutput) Reset()         { *m = CommonOutput{} }
func (m *CommonOutput) String() string { return proto.CompactTextString(m) }
func (*CommonOutput) ProtoMessage()    {}
func (*CommonOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eff423b0ca9b1f5, []int{0}
}

func (m *CommonOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonOutput.Unmarshal(m, b)
}
func (m *CommonOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonOutput.Marshal(b, m, deterministic)
}
func (m *CommonOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonOutput.Merge(m, src)
}
func (m *CommonOutput) XXX_Size() int {
	return xxx_messageInfo_CommonOutput.Size(m)
}
func (m *CommonOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CommonOutput proto.InternalMessageInfo

func (m *CommonOutput) GetHttpCode() int32 {
	if m != nil {
		return m.HttpCode
	}
	return 0
}

func (m *CommonOutput) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonOutput) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CommonOutput) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CommonOutput) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//------------------发送验证码-----------------
type SendMobileCodeIn struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Times                int32    `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	Timediff             int64    `protobuf:"varint,3,opt,name=timediff,proto3" json:"timediff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMobileCodeIn) Reset()         { *m = SendMobileCodeIn{} }
func (m *SendMobileCodeIn) String() string { return proto.CompactTextString(m) }
func (*SendMobileCodeIn) ProtoMessage()    {}
func (*SendMobileCodeIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eff423b0ca9b1f5, []int{1}
}

func (m *SendMobileCodeIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMobileCodeIn.Unmarshal(m, b)
}
func (m *SendMobileCodeIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMobileCodeIn.Marshal(b, m, deterministic)
}
func (m *SendMobileCodeIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMobileCodeIn.Merge(m, src)
}
func (m *SendMobileCodeIn) XXX_Size() int {
	return xxx_messageInfo_SendMobileCodeIn.Size(m)
}
func (m *SendMobileCodeIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMobileCodeIn.DiscardUnknown(m)
}

var xxx_messageInfo_SendMobileCodeIn proto.InternalMessageInfo

func (m *SendMobileCodeIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SendMobileCodeIn) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *SendMobileCodeIn) GetTimediff() int64 {
	if m != nil {
		return m.Timediff
	}
	return 0
}

//------------------get code -------------------
type IsMobileCodeOkIn struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Timediff             int32    `protobuf:"varint,3,opt,name=timediff,proto3" json:"timediff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsMobileCodeOkIn) Reset()         { *m = IsMobileCodeOkIn{} }
func (m *IsMobileCodeOkIn) String() string { return proto.CompactTextString(m) }
func (*IsMobileCodeOkIn) ProtoMessage()    {}
func (*IsMobileCodeOkIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eff423b0ca9b1f5, []int{2}
}

func (m *IsMobileCodeOkIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsMobileCodeOkIn.Unmarshal(m, b)
}
func (m *IsMobileCodeOkIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsMobileCodeOkIn.Marshal(b, m, deterministic)
}
func (m *IsMobileCodeOkIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsMobileCodeOkIn.Merge(m, src)
}
func (m *IsMobileCodeOkIn) XXX_Size() int {
	return xxx_messageInfo_IsMobileCodeOkIn.Size(m)
}
func (m *IsMobileCodeOkIn) XXX_DiscardUnknown() {
	xxx_messageInfo_IsMobileCodeOkIn.DiscardUnknown(m)
}

var xxx_messageInfo_IsMobileCodeOkIn proto.InternalMessageInfo

func (m *IsMobileCodeOkIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *IsMobileCodeOkIn) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *IsMobileCodeOkIn) GetTimediff() int32 {
	if m != nil {
		return m.Timediff
	}
	return 0
}

func init() {
	proto.RegisterType((*CommonOutput)(nil), "jz.micro.jzback.srv.base.CommonOutput")
	proto.RegisterType((*SendMobileCodeIn)(nil), "jz.micro.jzback.srv.base.SendMobileCodeIn")
	proto.RegisterType((*IsMobileCodeOkIn)(nil), "jz.micro.jzback.srv.base.IsMobileCodeOkIn")
}

func init() { proto.RegisterFile("base_ex.proto", fileDescriptor_8eff423b0ca9b1f5) }

var fileDescriptor_8eff423b0ca9b1f5 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xa9, 0x5d, 0xc7, 0xfa, 0x98, 0x50, 0x82, 0x48, 0xd0, 0x4b, 0xe9, 0xa9, 0xa7, 0x5c,
	0xfc, 0x13, 0x76, 0xda, 0x41, 0x06, 0xf1, 0x26, 0xc2, 0x48, 0x9b, 0x4c, 0xb3, 0x2d, 0x4d, 0x69,
	0xde, 0x44, 0x06, 0xfe, 0xef, 0x92, 0x67, 0x70, 0xe2, 0xc1, 0xdb, 0xf7, 0xfb, 0xc8, 0xfb, 0xbe,
	0xbc, 0x07, 0xd7, 0x9d, 0x0a, 0x66, 0x6b, 0x3e, 0xc4, 0x38, 0x79, 0xf4, 0x8c, 0xef, 0xcf, 0xc2,
	0xd9, 0x7e, 0xf2, 0x62, 0x7f, 0xee, 0x54, 0x7f, 0x10, 0x61, 0x7a, 0x17, 0xf1, 0x49, 0xf3, 0x09,
	0xcb, 0x95, 0x77, 0xce, 0x0f, 0x9b, 0x13, 0x8e, 0x27, 0x64, 0xf7, 0x50, 0xbe, 0x21, 0x8e, 0xdb,
	0xde, 0x6b, 0xc3, 0xb3, 0x3a, 0x6b, 0x0b, 0xb9, 0x88, 0xc6, 0xca, 0x6b, 0xc3, 0x18, 0xcc, 0xc8,
	0xbf, 0x22, 0x9f, 0x34, 0xab, 0x20, 0x77, 0xe1, 0x95, 0xe7, 0x75, 0xd6, 0x96, 0x32, 0x4a, 0x76,
	0x0b, 0x73, 0x6d, 0x50, 0xd9, 0x23, 0x9f, 0x91, 0x99, 0x28, 0x4e, 0x6b, 0x85, 0x8a, 0x17, 0x75,
	0xd6, 0x2e, 0x25, 0xe9, 0xe6, 0x05, 0xaa, 0x27, 0x33, 0xe8, 0x47, 0xdf, 0xd9, 0xa3, 0x89, 0x1d,
	0xeb, 0x21, 0xce, 0x3b, 0x62, 0xea, 0x2f, 0x65, 0x22, 0x76, 0x03, 0x05, 0x5a, 0x67, 0x42, 0xaa,
	0xff, 0x06, 0x76, 0x07, 0x8b, 0x28, 0xb4, 0xdd, 0xed, 0xe8, 0x13, 0xb9, 0xfc, 0xe1, 0xe6, 0x19,
	0xaa, 0x75, 0xb8, 0x64, 0x6f, 0x0e, 0xff, 0xa4, 0xff, 0xde, 0xad, 0x4c, 0xbb, 0xfd, 0xcd, 0x2e,
	0x2e, 0xd9, 0xdd, 0x9c, 0x2e, 0xfb, 0xf0, 0x15, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x16, 0x15, 0x2c,
	0x6a, 0x01, 0x00, 0x00,
}
