// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: base.proto

package jz_micro_jzback_srv_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Base service

type BaseService interface {
	SendMobileCode(ctx context.Context, in *SendMobileCodeIn, opts ...client.CallOption) (*CommonOutput, error)
	IsMobileCodeOk(ctx context.Context, in *IsMobileCodeOkIn, opts ...client.CallOption) (*CommonOutput, error)
}

type baseService struct {
	c    client.Client
	name string
}

func NewBaseService(name string, c client.Client) BaseService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "jz.micro.jzback.srv.base"
	}
	return &baseService{
		c:    c,
		name: name,
	}
}

func (c *baseService) SendMobileCode(ctx context.Context, in *SendMobileCodeIn, opts ...client.CallOption) (*CommonOutput, error) {
	req := c.c.NewRequest(c.name, "Base.SendMobileCode", in)
	out := new(CommonOutput)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseService) IsMobileCodeOk(ctx context.Context, in *IsMobileCodeOkIn, opts ...client.CallOption) (*CommonOutput, error) {
	req := c.c.NewRequest(c.name, "Base.IsMobileCodeOk", in)
	out := new(CommonOutput)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Base service

type BaseHandler interface {
	SendMobileCode(context.Context, *SendMobileCodeIn, *CommonOutput) error
	IsMobileCodeOk(context.Context, *IsMobileCodeOkIn, *CommonOutput) error
}

func RegisterBaseHandler(s server.Server, hdlr BaseHandler, opts ...server.HandlerOption) error {
	type base interface {
		SendMobileCode(ctx context.Context, in *SendMobileCodeIn, out *CommonOutput) error
		IsMobileCodeOk(ctx context.Context, in *IsMobileCodeOkIn, out *CommonOutput) error
	}
	type Base struct {
		base
	}
	h := &baseHandler{hdlr}
	return s.Handle(s.NewHandler(&Base{h}, opts...))
}

type baseHandler struct {
	BaseHandler
}

func (h *baseHandler) SendMobileCode(ctx context.Context, in *SendMobileCodeIn, out *CommonOutput) error {
	return h.BaseHandler.SendMobileCode(ctx, in, out)
}

func (h *baseHandler) IsMobileCodeOk(ctx context.Context, in *IsMobileCodeOkIn, out *CommonOutput) error {
	return h.BaseHandler.IsMobileCodeOk(ctx, in, out)
}
