// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mall.proto

package ds_srv_mall

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errex if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductByID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Lat1                 string   `protobuf:"bytes,2,opt,name=lat1,proto3" json:"lat1,omitempty"`
	Lng1                 string   `protobuf:"bytes,3,opt,name=lng1,proto3" json:"lng1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductByID) Reset()         { *m = ProductByID{} }
func (m *ProductByID) String() string { return proto.CompactTextString(m) }
func (*ProductByID) ProtoMessage()    {}
func (*ProductByID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{0}
}

func (m *ProductByID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductByID.Unmarshal(m, b)
}
func (m *ProductByID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductByID.Marshal(b, m, deterministic)
}
func (m *ProductByID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductByID.Merge(m, src)
}
func (m *ProductByID) XXX_Size() int {
	return xxx_messageInfo_ProductByID.Size(m)
}
func (m *ProductByID) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductByID.DiscardUnknown(m)
}

var xxx_messageInfo_ProductByID proto.InternalMessageInfo

func (m *ProductByID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProductByID) GetLat1() string {
	if m != nil {
		return m.Lat1
	}
	return ""
}

func (m *ProductByID) GetLng1() string {
	if m != nil {
		return m.Lng1
	}
	return ""
}

type RequestID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestID) Reset()         { *m = RequestID{} }
func (m *RequestID) String() string { return proto.CompactTextString(m) }
func (*RequestID) ProtoMessage()    {}
func (*RequestID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{1}
}

func (m *RequestID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestID.Unmarshal(m, b)
}
func (m *RequestID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestID.Marshal(b, m, deterministic)
}
func (m *RequestID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestID.Merge(m, src)
}
func (m *RequestID) XXX_Size() int {
	return xxx_messageInfo_RequestID.Size(m)
}
func (m *RequestID) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestID.DiscardUnknown(m)
}

var xxx_messageInfo_RequestID proto.InternalMessageInfo

func (m *RequestID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type RequestAddressID struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddressID) Reset()         { *m = RequestAddressID{} }
func (m *RequestAddressID) String() string { return proto.CompactTextString(m) }
func (*RequestAddressID) ProtoMessage()    {}
func (*RequestAddressID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{2}
}

func (m *RequestAddressID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddressID.Unmarshal(m, b)
}
func (m *RequestAddressID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddressID.Marshal(b, m, deterministic)
}
func (m *RequestAddressID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddressID.Merge(m, src)
}
func (m *RequestAddressID) XXX_Size() int {
	return xxx_messageInfo_RequestAddressID.Size(m)
}
func (m *RequestAddressID) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddressID.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddressID proto.InternalMessageInfo

func (m *RequestAddressID) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Response struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SelectProductRequest struct {
	ProductName          string   `protobuf:"bytes,1,opt,name=ProductName,proto3" json:"ProductName,omitempty"`
	BranchID             int64    `protobuf:"varint,2,opt,name=BranchID,proto3" json:"BranchID,omitempty"`
	BranchName           string   `protobuf:"bytes,3,opt,name=BranchName,proto3" json:"BranchName,omitempty"`
	ProductType          int32    `protobuf:"varint,4,opt,name=ProductType,proto3" json:"ProductType,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
	IsOnSale             int32    `protobuf:"varint,6,opt,name=IsOnSale,proto3" json:"IsOnSale,omitempty"`
	PageSize             int32    `protobuf:"varint,7,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum              int32    `protobuf:"varint,8,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	IsRecommend          int32    `protobuf:"varint,9,opt,name=IsRecommend,proto3" json:"IsRecommend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectProductRequest) Reset()         { *m = SelectProductRequest{} }
func (m *SelectProductRequest) String() string { return proto.CompactTextString(m) }
func (*SelectProductRequest) ProtoMessage()    {}
func (*SelectProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{4}
}

func (m *SelectProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectProductRequest.Unmarshal(m, b)
}
func (m *SelectProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectProductRequest.Marshal(b, m, deterministic)
}
func (m *SelectProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectProductRequest.Merge(m, src)
}
func (m *SelectProductRequest) XXX_Size() int {
	return xxx_messageInfo_SelectProductRequest.Size(m)
}
func (m *SelectProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectProductRequest proto.InternalMessageInfo

func (m *SelectProductRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *SelectProductRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

func (m *SelectProductRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *SelectProductRequest) GetProductType() int32 {
	if m != nil {
		return m.ProductType
	}
	return 0
}

func (m *SelectProductRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *SelectProductRequest) GetIsOnSale() int32 {
	if m != nil {
		return m.IsOnSale
	}
	return 0
}

func (m *SelectProductRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SelectProductRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *SelectProductRequest) GetIsRecommend() int32 {
	if m != nil {
		return m.IsRecommend
	}
	return 0
}

type CreateAddressRequest struct {
	UserAccount          string   `protobuf:"bytes,1,opt,name=UserAccount,proto3" json:"UserAccount,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserAlias            string   `protobuf:"bytes,3,opt,name=UserAlias,proto3" json:"UserAlias,omitempty"`
	Province             string   `protobuf:"bytes,4,opt,name=Province,proto3" json:"Province,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	Aera                 string   `protobuf:"bytes,6,opt,name=Aera,proto3" json:"Aera,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=Address,proto3" json:"Address,omitempty"`
	Tel                  string   `protobuf:"bytes,8,opt,name=Tel,proto3" json:"Tel,omitempty"`
	Sex                  int32    `protobuf:"varint,9,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Label                int32    `protobuf:"varint,10,opt,name=Label,proto3" json:"Label,omitempty"`
	TelName              string   `protobuf:"bytes,11,opt,name=TelName,proto3" json:"TelName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAddressRequest) Reset()         { *m = CreateAddressRequest{} }
func (m *CreateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAddressRequest) ProtoMessage()    {}
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{5}
}

func (m *CreateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAddressRequest.Unmarshal(m, b)
}
func (m *CreateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAddressRequest.Marshal(b, m, deterministic)
}
func (m *CreateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAddressRequest.Merge(m, src)
}
func (m *CreateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAddressRequest.Size(m)
}
func (m *CreateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAddressRequest proto.InternalMessageInfo

func (m *CreateAddressRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *CreateAddressRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateAddressRequest) GetUserAlias() string {
	if m != nil {
		return m.UserAlias
	}
	return ""
}

func (m *CreateAddressRequest) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *CreateAddressRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateAddressRequest) GetAera() string {
	if m != nil {
		return m.Aera
	}
	return ""
}

func (m *CreateAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateAddressRequest) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *CreateAddressRequest) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *CreateAddressRequest) GetLabel() int32 {
	if m != nil {
		return m.Label
	}
	return 0
}

func (m *CreateAddressRequest) GetTelName() string {
	if m != nil {
		return m.TelName
	}
	return ""
}

type CreateOrderRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ProductID            int64    `protobuf:"varint,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	ProductNum           int32    `protobuf:"varint,3,opt,name=ProductNum,proto3" json:"ProductNum,omitempty"`
	AddressID            int64    `protobuf:"varint,4,opt,name=AddressID,proto3" json:"AddressID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{6}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateOrderRequest) GetProductID() int64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *CreateOrderRequest) GetProductNum() int32 {
	if m != nil {
		return m.ProductNum
	}
	return 0
}

func (m *CreateOrderRequest) GetAddressID() int64 {
	if m != nil {
		return m.AddressID
	}
	return 0
}

type SelectOrderRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrderState           int32    `protobuf:"varint,2,opt,name=OrderState,proto3" json:"OrderState,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum              int32    `protobuf:"varint,4,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	CreateStartTime      string   `protobuf:"bytes,5,opt,name=CreateStartTime,proto3" json:"CreateStartTime,omitempty"`
	CreateEndTime        string   `protobuf:"bytes,6,opt,name=CreateEndTime,proto3" json:"CreateEndTime,omitempty"`
	CompleteStartTime    string   `protobuf:"bytes,7,opt,name=CompleteStartTime,proto3" json:"CompleteStartTime,omitempty"`
	CompleteEndTime      string   `protobuf:"bytes,8,opt,name=CompleteEndTime,proto3" json:"CompleteEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectOrderRequest) Reset()         { *m = SelectOrderRequest{} }
func (m *SelectOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SelectOrderRequest) ProtoMessage()    {}
func (*SelectOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{7}
}

func (m *SelectOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectOrderRequest.Unmarshal(m, b)
}
func (m *SelectOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectOrderRequest.Marshal(b, m, deterministic)
}
func (m *SelectOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectOrderRequest.Merge(m, src)
}
func (m *SelectOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SelectOrderRequest.Size(m)
}
func (m *SelectOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectOrderRequest proto.InternalMessageInfo

func (m *SelectOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SelectOrderRequest) GetOrderState() int32 {
	if m != nil {
		return m.OrderState
	}
	return 0
}

func (m *SelectOrderRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SelectOrderRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *SelectOrderRequest) GetCreateStartTime() string {
	if m != nil {
		return m.CreateStartTime
	}
	return ""
}

func (m *SelectOrderRequest) GetCreateEndTime() string {
	if m != nil {
		return m.CreateEndTime
	}
	return ""
}

func (m *SelectOrderRequest) GetCompleteStartTime() string {
	if m != nil {
		return m.CompleteStartTime
	}
	return ""
}

func (m *SelectOrderRequest) GetCompleteEndTime() string {
	if m != nil {
		return m.CompleteEndTime
	}
	return ""
}

type PayOrderRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrderID              int64    `protobuf:"varint,2,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	TransactionPassword  string   `protobuf:"bytes,3,opt,name=TransactionPassword,proto3" json:"TransactionPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderRequest) Reset()         { *m = PayOrderRequest{} }
func (m *PayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderRequest) ProtoMessage()    {}
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{8}
}

func (m *PayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderRequest.Unmarshal(m, b)
}
func (m *PayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderRequest.Merge(m, src)
}
func (m *PayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderRequest.Size(m)
}
func (m *PayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderRequest proto.InternalMessageInfo

func (m *PayOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PayOrderRequest) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *PayOrderRequest) GetTransactionPassword() string {
	if m != nil {
		return m.TransactionPassword
	}
	return ""
}

type ResponseID struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseID) Reset()         { *m = ResponseID{} }
func (m *ResponseID) String() string { return proto.CompactTextString(m) }
func (*ResponseID) ProtoMessage()    {}
func (*ResponseID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eca37126ce3a5a2, []int{9}
}

func (m *ResponseID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseID.Unmarshal(m, b)
}
func (m *ResponseID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseID.Marshal(b, m, deterministic)
}
func (m *ResponseID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseID.Merge(m, src)
}
func (m *ResponseID) XXX_Size() int {
	return xxx_messageInfo_ResponseID.Size(m)
}
func (m *ResponseID) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseID.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseID proto.InternalMessageInfo

func (m *ResponseID) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseID) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductByID)(nil), "ds.srv.mall.productByID")
	proto.RegisterType((*RequestID)(nil), "ds.srv.mall.requestID")
	proto.RegisterType((*RequestAddressID)(nil), "ds.srv.mall.requestAddressID")
	proto.RegisterType((*Response)(nil), "ds.srv.mall.response")
	proto.RegisterType((*SelectProductRequest)(nil), "ds.srv.mall.selectProductRequest")
	proto.RegisterType((*CreateAddressRequest)(nil), "ds.srv.mall.createAddressRequest")
	proto.RegisterType((*CreateOrderRequest)(nil), "ds.srv.mall.createOrderRequest")
	proto.RegisterType((*SelectOrderRequest)(nil), "ds.srv.mall.selectOrderRequest")
	proto.RegisterType((*PayOrderRequest)(nil), "ds.srv.mall.payOrderRequest")
	proto.RegisterType((*ResponseID)(nil), "ds.srv.mall.responseID")
}

func init() { proto.RegisterFile("mall.proto", fileDescriptor_8eca37126ce3a5a2) }

var fileDescriptor_8eca37126ce3a5a2 = []byte{
	// 755 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0x13, 0x31,
	0x10, 0x25, 0xb7, 0x36, 0x3b, 0xe9, 0x0d, 0x13, 0xd0, 0xaa, 0x94, 0x52, 0x56, 0x3c, 0x54, 0x08,
	0x45, 0x14, 0x10, 0xef, 0x69, 0x52, 0x55, 0x2b, 0xaa, 0xb6, 0x72, 0xc2, 0x07, 0xb8, 0xbb, 0xa3,
	0x36, 0x62, 0x2f, 0xc1, 0x76, 0x0a, 0xe1, 0x0b, 0x78, 0xe6, 0x0b, 0x10, 0x8f, 0x7c, 0x25, 0xf2,
	0x65, 0x13, 0x6f, 0x9b, 0x54, 0x55, 0xdf, 0x3c, 0xc7, 0xb3, 0x67, 0x66, 0xce, 0x8c, 0x27, 0x01,
	0x48, 0x59, 0x92, 0x74, 0xc6, 0x3c, 0x97, 0x39, 0x69, 0xc5, 0xa2, 0x23, 0xf8, 0x75, 0x47, 0x41,
	0xc1, 0x11, 0xb4, 0xc6, 0x3c, 0x8f, 0x27, 0x91, 0x3c, 0x9c, 0x86, 0x7d, 0xb2, 0x01, 0xd5, 0xb0,
	0xef, 0x57, 0xf6, 0x2a, 0xfb, 0x35, 0x5a, 0x0d, 0xfb, 0x84, 0x40, 0x3d, 0x61, 0xf2, 0xc0, 0xaf,
	0xee, 0x55, 0xf6, 0x3d, 0xaa, 0xcf, 0x1a, 0xcb, 0x2e, 0x0f, 0xfc, 0x9a, 0xc5, 0xb2, 0xcb, 0x83,
	0xe0, 0x39, 0x78, 0x1c, 0xbf, 0x4d, 0x50, 0xc8, 0xdb, 0x24, 0xc1, 0x1b, 0xd8, 0xb2, 0x97, 0xdd,
	0x38, 0xe6, 0x28, 0x44, 0xd8, 0x27, 0xcf, 0x60, 0xe5, 0x8b, 0x40, 0x6e, 0xfd, 0x3c, 0x6a, 0xad,
	0xe0, 0x23, 0x34, 0x39, 0x8a, 0x71, 0x9e, 0x09, 0x54, 0x81, 0x62, 0x26, 0x99, 0xf6, 0x58, 0xa3,
	0xfa, 0x4c, 0xda, 0xd0, 0xe8, 0xe5, 0x93, 0x4c, 0xea, 0x8c, 0x1a, 0xd4, 0x18, 0xc1, 0xdf, 0x2a,
	0xb4, 0x05, 0x26, 0x18, 0xc9, 0x73, 0x53, 0x0c, 0x35, 0xf1, 0xc8, 0x1e, 0xb4, 0x2c, 0x72, 0xca,
	0x52, 0xb4, 0xb1, 0x5c, 0x88, 0x6c, 0x43, 0xf3, 0x90, 0xb3, 0x2c, 0xba, 0x0a, 0xfb, 0x9a, 0xb3,
	0x46, 0x67, 0x36, 0xd9, 0x05, 0x30, 0x67, 0xfd, 0xb1, 0xa9, 0xd7, 0x41, 0x1c, 0xf6, 0xe1, 0x74,
	0x8c, 0x7e, 0x5d, 0xa7, 0xe4, 0x42, 0xaa, 0x4c, 0x8a, 0x29, 0xe3, 0x5f, 0xfd, 0x86, 0x29, 0xd3,
	0x58, 0x2a, 0x6a, 0x28, 0xce, 0xb2, 0x01, 0x4b, 0xd0, 0x5f, 0xd1, 0x9f, 0xcd, 0x6c, 0x75, 0x77,
	0xce, 0x2e, 0x71, 0x30, 0xfa, 0x89, 0xfe, 0xaa, 0xb9, 0x2b, 0x6c, 0xe2, 0xc3, 0xaa, 0x3a, 0x9f,
	0x4e, 0x52, 0xbf, 0xa9, 0xaf, 0x0a, 0x53, 0xe5, 0x12, 0x0a, 0x8a, 0x51, 0x9e, 0xa6, 0x98, 0xc5,
	0xbe, 0x67, 0x72, 0x71, 0xa0, 0xe0, 0x4f, 0x15, 0xda, 0x11, 0x47, 0x26, 0xd1, 0xb6, 0xc1, 0x11,
	0x49, 0xa9, 0xdf, 0x8d, 0x22, 0xad, 0xac, 0x15, 0xc9, 0x81, 0x9c, 0x6e, 0x55, 0xdd, 0x6e, 0x91,
	0x1d, 0xf0, 0xb4, 0x5b, 0x32, 0x62, 0xc2, 0xea, 0x33, 0x07, 0x74, 0x21, 0x3c, 0xbf, 0x1e, 0x65,
	0x91, 0xd1, 0xc6, 0xa3, 0x33, 0x5b, 0xf5, 0xb6, 0x37, 0x92, 0x53, 0x2b, 0x8b, 0x3e, 0x2b, 0xac,
	0x8b, 0x9c, 0x69, 0x41, 0x3c, 0xaa, 0xcf, 0xaa, 0x60, 0x9b, 0xad, 0xd6, 0xc2, 0xa3, 0x85, 0x49,
	0xb6, 0xa0, 0x36, 0xc4, 0x44, 0xcb, 0xe0, 0x51, 0x75, 0x54, 0xc8, 0x00, 0x7f, 0xd8, 0xd2, 0xd5,
	0x51, 0x4d, 0xcb, 0x09, 0xbb, 0xc0, 0xc4, 0x07, 0x33, 0x2d, 0xda, 0x50, 0x9c, 0x43, 0x4c, 0x74,
	0x4f, 0x5b, 0x86, 0xd3, 0x9a, 0xc1, 0xaf, 0x0a, 0x10, 0x23, 0xd1, 0x19, 0x8f, 0x91, 0x17, 0x02,
	0x2d, 0x19, 0x56, 0x55, 0xbe, 0x6d, 0xf6, 0x6c, 0x78, 0xe6, 0x80, 0x9a, 0x9e, 0x62, 0xd0, 0x26,
	0xa9, 0x56, 0xa7, 0x41, 0x1d, 0x44, 0x7d, 0x3d, 0x7b, 0x0f, 0x5a, 0x9f, 0x1a, 0x9d, 0x03, 0xc1,
	0xbf, 0x2a, 0x10, 0x33, 0xd2, 0xf7, 0x4a, 0x65, 0x17, 0x40, 0xfb, 0x0d, 0x24, 0x93, 0x68, 0x1f,
	0x87, 0x83, 0x94, 0x86, 0xaa, 0xb6, 0x7c, 0xa8, 0xea, 0xe5, 0xa1, 0xda, 0x87, 0xcd, 0x9e, 0x96,
	0x63, 0x20, 0x19, 0x97, 0xc3, 0x51, 0x8a, 0xb6, 0x61, 0x37, 0x61, 0xf2, 0x1a, 0xd6, 0x0d, 0x74,
	0x94, 0xc5, 0xda, 0xcf, 0x34, 0xb1, 0x0c, 0x92, 0xb7, 0xf0, 0xb8, 0x97, 0xa7, 0xe3, 0x04, 0x5d,
	0x46, 0xd3, 0xd7, 0xdb, 0x17, 0x3a, 0xba, 0x05, 0x0b, 0xd6, 0xa6, 0x8d, 0x5e, 0x86, 0x83, 0x09,
	0x6c, 0x8e, 0xd9, 0xf4, 0x5e, 0x42, 0xf9, 0xb0, 0xaa, 0xfd, 0x66, 0x1d, 0x2b, 0x4c, 0xf2, 0x0e,
	0x9e, 0x0c, 0x39, 0xcb, 0x04, 0x8b, 0xe4, 0x28, 0xcf, 0xce, 0x99, 0x10, 0xdf, 0x73, 0x1e, 0xdb,
	0xb1, 0x5e, 0x74, 0x15, 0x7c, 0x02, 0x28, 0x96, 0x95, 0xd9, 0x95, 0xf7, 0x5b, 0x57, 0xef, 0x7f,
	0x37, 0xa0, 0xae, 0xb6, 0x2f, 0xe9, 0xc1, 0xc6, 0x31, 0x16, 0x3b, 0x4b, 0x2f, 0x60, 0xbf, 0xe3,
	0x6c, 0xe7, 0x8e, 0xb3, 0x9a, 0xb7, 0x9f, 0x96, 0x6e, 0x8a, 0xb8, 0xc1, 0x23, 0x12, 0x42, 0x7b,
	0x4e, 0xd2, 0x47, 0xc9, 0x46, 0xc9, 0x43, 0xa9, 0x4e, 0x60, 0x63, 0xe0, 0xae, 0x51, 0x41, 0x5e,
	0x95, 0x5c, 0x17, 0xed, 0xd8, 0xe5, 0x6c, 0x9f, 0x8b, 0x99, 0x28, 0x9e, 0x6c, 0x99, 0x6c, 0xd1,
	0x2e, 0x5a, 0x4e, 0x76, 0x0c, 0xeb, 0x03, 0x64, 0x3c, 0xba, 0x2a, 0xc8, 0x5e, 0xdc, 0xf0, 0x2c,
	0xff, 0xc0, 0xdc, 0x45, 0xd4, 0xea, 0xcd, 0x9f, 0x38, 0x79, 0xb9, 0x20, 0x27, 0x77, 0x90, 0xee,
	0x24, 0x32, 0x19, 0x2d, 0x22, 0xba, 0xfd, 0x74, 0x97, 0x13, 0x75, 0xd5, 0xdb, 0x34, 0xd3, 0x4b,
	0x76, 0xca, 0x4d, 0x2b, 0x0f, 0xf5, 0x5d, 0x14, 0x6b, 0xc7, 0x68, 0xc2, 0x3d, 0xb0, 0xf7, 0x17,
	0x2b, 0xfa, 0xdf, 0xc1, 0x87, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x16, 0xf2, 0x2e, 0x2b,
	0x08, 0x00, 0x00,
}
