// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_ex.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//message GetBackUerInfoInput {
//}
//message GetChannelInfoInput {
//}
//message GetRoleInfoInput {
//}
//
//message BackLoginInput{
//    string back_name=1;
//    string password=2;
//}
//message AddAccessInput {
//    string acs_name = 1;
//    string acs_tag = 2;
//}
//message DeleteAccessInput {
//    string acs_name = 1;
//    string acs_tag = 2;
//}
//message GetAccessListInput {
//}
//message GetRoleListInput {
//}
//message AddRoleInput {
//    string role_name = 1;
//}
//message EditRoleInput {
//    string rolename_old = 1;
//    string rolename_new = 2;
//}
//message DeleteRoleInput {
//    string rolename = 1;
//}
//message AddUserInput {
//    string real_name = 1;
//    int32 gender = 2;
//    int32 age = 3;
//    string id_card = 4;
//    string mobile = 5;
//    string address = 6;
//    string role_name = 7;
//    string user_name = 8;
//    string password = 9;
//    string nick_name = 10;
//    string avatar = 11;
//    int32 channel_id = 12;
//    string last_login = 13;
//    int32 status = 14;
//}
//message DelUserInput {
//    string real_name = 1;
//    string mobile = 2;
//    string user_name = 3;
//    string nick_name = 4;
//    int32 status = 5;
//}
type CommonOutput struct {
	HttpCode             int32    `protobuf:"varint,1,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Detail               string   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonOutput) Reset()         { *m = CommonOutput{} }
func (m *CommonOutput) String() string { return proto.CompactTextString(m) }
func (*CommonOutput) ProtoMessage()    {}
func (*CommonOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{0}
}

func (m *CommonOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonOutput.Unmarshal(m, b)
}
func (m *CommonOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonOutput.Marshal(b, m, deterministic)
}
func (m *CommonOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonOutput.Merge(m, src)
}
func (m *CommonOutput) XXX_Size() int {
	return xxx_messageInfo_CommonOutput.Size(m)
}
func (m *CommonOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CommonOutput proto.InternalMessageInfo

func (m *CommonOutput) GetHttpCode() int32 {
	if m != nil {
		return m.HttpCode
	}
	return 0
}

func (m *CommonOutput) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonOutput) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CommonOutput) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *CommonOutput) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//**********************************************************
type MultiLoginMobileInput struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiLoginMobileInput) Reset()         { *m = MultiLoginMobileInput{} }
func (m *MultiLoginMobileInput) String() string { return proto.CompactTextString(m) }
func (*MultiLoginMobileInput) ProtoMessage()    {}
func (*MultiLoginMobileInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{1}
}

func (m *MultiLoginMobileInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiLoginMobileInput.Unmarshal(m, b)
}
func (m *MultiLoginMobileInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiLoginMobileInput.Marshal(b, m, deterministic)
}
func (m *MultiLoginMobileInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiLoginMobileInput.Merge(m, src)
}
func (m *MultiLoginMobileInput) XXX_Size() int {
	return xxx_messageInfo_MultiLoginMobileInput.Size(m)
}
func (m *MultiLoginMobileInput) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiLoginMobileInput.DiscardUnknown(m)
}

var xxx_messageInfo_MultiLoginMobileInput proto.InternalMessageInfo

func (m *MultiLoginMobileInput) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MultiLoginMobileInput) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

//**********************************************************
type SingleLoginGuestInput struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceType           string   `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Channel              int32    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleLoginGuestInput) Reset()         { *m = SingleLoginGuestInput{} }
func (m *SingleLoginGuestInput) String() string { return proto.CompactTextString(m) }
func (*SingleLoginGuestInput) ProtoMessage()    {}
func (*SingleLoginGuestInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{2}
}

func (m *SingleLoginGuestInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleLoginGuestInput.Unmarshal(m, b)
}
func (m *SingleLoginGuestInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleLoginGuestInput.Marshal(b, m, deterministic)
}
func (m *SingleLoginGuestInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleLoginGuestInput.Merge(m, src)
}
func (m *SingleLoginGuestInput) XXX_Size() int {
	return xxx_messageInfo_SingleLoginGuestInput.Size(m)
}
func (m *SingleLoginGuestInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleLoginGuestInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleLoginGuestInput proto.InternalMessageInfo

func (m *SingleLoginGuestInput) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SingleLoginGuestInput) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *SingleLoginGuestInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

type SingleLoginMobileInput struct {
	Channel              int32    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleLoginMobileInput) Reset()         { *m = SingleLoginMobileInput{} }
func (m *SingleLoginMobileInput) String() string { return proto.CompactTextString(m) }
func (*SingleLoginMobileInput) ProtoMessage()    {}
func (*SingleLoginMobileInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{3}
}

func (m *SingleLoginMobileInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleLoginMobileInput.Unmarshal(m, b)
}
func (m *SingleLoginMobileInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleLoginMobileInput.Marshal(b, m, deterministic)
}
func (m *SingleLoginMobileInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleLoginMobileInput.Merge(m, src)
}
func (m *SingleLoginMobileInput) XXX_Size() int {
	return xxx_messageInfo_SingleLoginMobileInput.Size(m)
}
func (m *SingleLoginMobileInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleLoginMobileInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleLoginMobileInput proto.InternalMessageInfo

func (m *SingleLoginMobileInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SingleLoginMobileInput) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SingleLoginMobileInput) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SingleLoginAccountInput struct {
	Channel              int32    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	AccountId            string   `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Pwd                  string   `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleLoginAccountInput) Reset()         { *m = SingleLoginAccountInput{} }
func (m *SingleLoginAccountInput) String() string { return proto.CompactTextString(m) }
func (*SingleLoginAccountInput) ProtoMessage()    {}
func (*SingleLoginAccountInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{4}
}

func (m *SingleLoginAccountInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleLoginAccountInput.Unmarshal(m, b)
}
func (m *SingleLoginAccountInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleLoginAccountInput.Marshal(b, m, deterministic)
}
func (m *SingleLoginAccountInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleLoginAccountInput.Merge(m, src)
}
func (m *SingleLoginAccountInput) XXX_Size() int {
	return xxx_messageInfo_SingleLoginAccountInput.Size(m)
}
func (m *SingleLoginAccountInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleLoginAccountInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleLoginAccountInput proto.InternalMessageInfo

func (m *SingleLoginAccountInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SingleLoginAccountInput) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SingleLoginAccountInput) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

//******************手机号注册**********************************
type SingleRegistMobileInput struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Ver                  int32    `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	Channel              int32    `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Pid                  string   `protobuf:"bytes,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Timediff             int32    `protobuf:"varint,9,opt,name=timediff,proto3" json:"timediff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRegistMobileInput) Reset()         { *m = SingleRegistMobileInput{} }
func (m *SingleRegistMobileInput) String() string { return proto.CompactTextString(m) }
func (*SingleRegistMobileInput) ProtoMessage()    {}
func (*SingleRegistMobileInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{5}
}

func (m *SingleRegistMobileInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRegistMobileInput.Unmarshal(m, b)
}
func (m *SingleRegistMobileInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRegistMobileInput.Marshal(b, m, deterministic)
}
func (m *SingleRegistMobileInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRegistMobileInput.Merge(m, src)
}
func (m *SingleRegistMobileInput) XXX_Size() int {
	return xxx_messageInfo_SingleRegistMobileInput.Size(m)
}
func (m *SingleRegistMobileInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRegistMobileInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRegistMobileInput proto.InternalMessageInfo

func (m *SingleRegistMobileInput) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SingleRegistMobileInput) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SingleRegistMobileInput) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SingleRegistMobileInput) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *SingleRegistMobileInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SingleRegistMobileInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SingleRegistMobileInput) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *SingleRegistMobileInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SingleRegistMobileInput) GetTimediff() int32 {
	if m != nil {
		return m.Timediff
	}
	return 0
}

//******************账号密码注册********************
type SingleRegistAccountInput struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Ver                  int32    `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	Channel              int32    `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Pid                  string   `protobuf:"bytes,7,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRegistAccountInput) Reset()         { *m = SingleRegistAccountInput{} }
func (m *SingleRegistAccountInput) String() string { return proto.CompactTextString(m) }
func (*SingleRegistAccountInput) ProtoMessage()    {}
func (*SingleRegistAccountInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{6}
}

func (m *SingleRegistAccountInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRegistAccountInput.Unmarshal(m, b)
}
func (m *SingleRegistAccountInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRegistAccountInput.Marshal(b, m, deterministic)
}
func (m *SingleRegistAccountInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRegistAccountInput.Merge(m, src)
}
func (m *SingleRegistAccountInput) XXX_Size() int {
	return xxx_messageInfo_SingleRegistAccountInput.Size(m)
}
func (m *SingleRegistAccountInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRegistAccountInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRegistAccountInput proto.InternalMessageInfo

func (m *SingleRegistAccountInput) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SingleRegistAccountInput) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SingleRegistAccountInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SingleRegistAccountInput) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *SingleRegistAccountInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SingleRegistAccountInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SingleRegistAccountInput) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

//******************快速注册********************
type SingleRegistQuickInput struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ver                  int32    `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Channel              int32    `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Pid                  string   `protobuf:"bytes,5,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRegistQuickInput) Reset()         { *m = SingleRegistQuickInput{} }
func (m *SingleRegistQuickInput) String() string { return proto.CompactTextString(m) }
func (*SingleRegistQuickInput) ProtoMessage()    {}
func (*SingleRegistQuickInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c9202a3b8a61b8, []int{7}
}

func (m *SingleRegistQuickInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRegistQuickInput.Unmarshal(m, b)
}
func (m *SingleRegistQuickInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRegistQuickInput.Marshal(b, m, deterministic)
}
func (m *SingleRegistQuickInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRegistQuickInput.Merge(m, src)
}
func (m *SingleRegistQuickInput) XXX_Size() int {
	return xxx_messageInfo_SingleRegistQuickInput.Size(m)
}
func (m *SingleRegistQuickInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRegistQuickInput.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRegistQuickInput proto.InternalMessageInfo

func (m *SingleRegistQuickInput) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SingleRegistQuickInput) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *SingleRegistQuickInput) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *SingleRegistQuickInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SingleRegistQuickInput) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonOutput)(nil), "user.CommonOutput")
	proto.RegisterType((*MultiLoginMobileInput)(nil), "user.MultiLoginMobileInput")
	proto.RegisterType((*SingleLoginGuestInput)(nil), "user.SingleLoginGuestInput")
	proto.RegisterType((*SingleLoginMobileInput)(nil), "user.SingleLoginMobileInput")
	proto.RegisterType((*SingleLoginAccountInput)(nil), "user.SingleLoginAccountInput")
	proto.RegisterType((*SingleRegistMobileInput)(nil), "user.SingleRegistMobileInput")
	proto.RegisterType((*SingleRegistAccountInput)(nil), "user.SingleRegistAccountInput")
	proto.RegisterType((*SingleRegistQuickInput)(nil), "user.SingleRegistQuickInput")
}

func init() { proto.RegisterFile("user_ex.proto", fileDescriptor_b9c9202a3b8a61b8) }

var fileDescriptor_b9c9202a3b8a61b8 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcb, 0xee, 0xd2, 0x40,
	0x14, 0x87, 0x53, 0x7a, 0xa1, 0x3d, 0x62, 0x62, 0x26, 0x01, 0x27, 0x12, 0x23, 0xe9, 0x8a, 0x95,
	0x1b, 0x9f, 0xc0, 0xb0, 0x30, 0x24, 0x12, 0x63, 0x75, 0x2d, 0x29, 0x9d, 0xa1, 0x4c, 0x6c, 0x3b,
	0x4d, 0x3b, 0x05, 0x59, 0xb8, 0xf6, 0xb1, 0x7c, 0x21, 0x1f, 0xc2, 0xcc, 0xa5, 0x32, 0xd5, 0x8a,
	0x2e, 0xfe, 0xbb, 0xf3, 0x3b, 0x65, 0xce, 0xf9, 0xbe, 0x69, 0x03, 0x3c, 0xee, 0x5a, 0xda, 0xec,
	0xe9, 0x97, 0x97, 0x75, 0xc3, 0x05, 0x47, 0x9e, 0x8c, 0xf1, 0x57, 0x98, 0x6d, 0x78, 0x59, 0xf2,
	0xea, 0x5d, 0x27, 0xea, 0x4e, 0xa0, 0x25, 0x44, 0x27, 0x21, 0xea, 0x7d, 0xc6, 0x09, 0xc5, 0xce,
	0xca, 0x59, 0xfb, 0x49, 0x28, 0x1b, 0x1b, 0x4e, 0x28, 0x42, 0xe0, 0xa9, 0xfe, 0x44, 0xf5, 0x55,
	0x8d, 0x9e, 0x80, 0x5b, 0xb6, 0x39, 0x76, 0x57, 0xce, 0x3a, 0x4a, 0x64, 0x89, 0x16, 0x10, 0x10,
	0x2a, 0x52, 0x56, 0x60, 0x4f, 0x35, 0x4d, 0x92, 0xa7, 0x49, 0x2a, 0x52, 0xec, 0xaf, 0x9c, 0xf5,
	0x2c, 0x51, 0x75, 0xbc, 0x81, 0xf9, 0xae, 0x2b, 0x04, 0x7b, 0xcb, 0x73, 0x56, 0xed, 0xf8, 0x81,
	0x15, 0x74, 0x5b, 0x49, 0x8e, 0x05, 0x04, 0xa5, 0x8a, 0x0a, 0x22, 0x4a, 0x4c, 0x1a, 0x20, 0x44,
	0x1a, 0x21, 0xe6, 0x30, 0xff, 0xc0, 0xaa, 0xbc, 0xa0, 0x6a, 0xca, 0x9b, 0x8e, 0xb6, 0x42, 0x0f,
	0x59, 0x42, 0x44, 0xe8, 0x99, 0x65, 0x74, 0xcf, 0x88, 0x99, 0x13, 0xea, 0xc6, 0x96, 0xa0, 0x17,
	0xf0, 0xc8, 0x3c, 0x14, 0xd7, 0xba, 0x1f, 0x08, 0xba, 0xf5, 0xf1, 0x5a, 0x53, 0x84, 0x61, 0x9a,
	0x9d, 0xd2, 0xaa, 0xa2, 0x85, 0xb2, 0xf3, 0x93, 0x3e, 0xc6, 0x9f, 0x60, 0x61, 0x2d, 0xb4, 0xb1,
	0xff, 0x7a, 0xc6, 0x12, 0xf2, 0x46, 0x85, 0x7c, 0x4b, 0x88, 0xc0, 0x53, 0x6b, 0xfe, 0xeb, 0x2c,
	0xe3, 0x5d, 0x25, 0xfe, 0xb5, 0xe0, 0x39, 0x40, 0xaa, 0x7f, 0x29, 0x6d, 0xf5, 0x92, 0xc8, 0x74,
	0xb6, 0x44, 0xbe, 0xa7, 0xfa, 0x42, 0xcc, 0x1a, 0x59, 0xc6, 0x3f, 0x9c, 0x7e, 0x4d, 0x42, 0x73,
	0xd6, 0x0a, 0xdb, 0xe3, 0xee, 0xcd, 0xdd, 0x54, 0x26, 0xa3, 0x2a, 0xee, 0x4d, 0x45, 0xae, 0x3d,
	0xd3, 0x46, 0xe1, 0xf8, 0x89, 0x2c, 0x6d, 0x03, 0x7f, 0x68, 0x80, 0xc0, 0x53, 0xaf, 0x22, 0xd0,
	0xe7, 0x65, 0xad, 0xb0, 0x19, 0xc1, 0x53, 0x83, 0xcd, 0x08, 0x7a, 0x06, 0x61, 0x9d, 0xb6, 0xed,
	0x85, 0x37, 0x04, 0x87, 0x9a, 0xac, 0xcf, 0xf2, 0x99, 0x60, 0x25, 0x25, 0xec, 0x78, 0xc4, 0x91,
	0xfe, 0x78, 0xfb, 0x1c, 0x7f, 0x77, 0x00, 0xdb, 0xba, 0x83, 0x6b, 0xbd, 0xeb, 0x8b, 0x61, 0x6a,
	0xee, 0xd1, 0x08, 0xf7, 0x71, 0xc0, 0xe2, 0xfe, 0xc6, 0xf2, 0xe0, 0xe6, 0xf1, 0x37, 0xa7, 0xff,
	0xee, 0xb4, 0xc1, 0xfb, 0x8e, 0x65, 0x9f, 0xff, 0x83, 0xdf, 0x90, 0x4c, 0x46, 0x49, 0xdc, 0x71,
	0x12, 0xef, 0x4f, 0x12, 0xff, 0x17, 0xc9, 0x21, 0x50, 0x7f, 0x21, 0xaf, 0x7e, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x89, 0x4b, 0x30, 0xfb, 0x53, 0x04, 0x00, 0x00,
}
