// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nsq.proto

package go_micro_broker_nsq_srv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoEvent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoEvent) Reset()         { *m = DemoEvent{} }
func (m *DemoEvent) String() string { return proto.CompactTextString(m) }
func (*DemoEvent) ProtoMessage()    {}
func (*DemoEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f83e7c7ac3c992fd, []int{0}
}

func (m *DemoEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoEvent.Unmarshal(m, b)
}
func (m *DemoEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoEvent.Marshal(b, m, deterministic)
}
func (m *DemoEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoEvent.Merge(m, src)
}
func (m *DemoEvent) XXX_Size() int {
	return xxx_messageInfo_DemoEvent.Size(m)
}
func (m *DemoEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DemoEvent proto.InternalMessageInfo

func (m *DemoEvent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DemoEvent) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*DemoEvent)(nil), "go.micro.broker.nsq.srv.DemoEvent")
}

func init() { proto.RegisterFile("nsq.proto", fileDescriptor_f83e7c7ac3c992fd) }

var fileDescriptor_f83e7c7ac3c992fd = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2b, 0x2e, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7,
	0x4b, 0x2a, 0xca, 0xcf, 0x4e, 0x2d, 0xd2, 0x03, 0x49, 0x15, 0x17, 0x95, 0x29, 0x99, 0x72, 0x71,
	0xba, 0xa4, 0xe6, 0xe6, 0xbb, 0x96, 0xa5, 0xe6, 0x95, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x27, 0x97, 0x16,
	0x15, 0xa5, 0xe6, 0x95, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x49, 0x6c, 0x60,
	0x63, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xa6, 0x79, 0x0b, 0x63, 0x00, 0x00, 0x00,
}
