// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package ds_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errex if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*******************************
type SetPaypwdIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Paypwd               string   `protobuf:"bytes,3,opt,name=paypwd,proto3" json:"paypwd,omitempty"`
	Vfcode               string   `protobuf:"bytes,4,opt,name=vfcode,proto3" json:"vfcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPaypwdIn) Reset()         { *m = SetPaypwdIn{} }
func (m *SetPaypwdIn) String() string { return proto.CompactTextString(m) }
func (*SetPaypwdIn) ProtoMessage()    {}
func (*SetPaypwdIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *SetPaypwdIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPaypwdIn.Unmarshal(m, b)
}
func (m *SetPaypwdIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPaypwdIn.Marshal(b, m, deterministic)
}
func (m *SetPaypwdIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPaypwdIn.Merge(m, src)
}
func (m *SetPaypwdIn) XXX_Size() int {
	return xxx_messageInfo_SetPaypwdIn.Size(m)
}
func (m *SetPaypwdIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPaypwdIn.DiscardUnknown(m)
}

var xxx_messageInfo_SetPaypwdIn proto.InternalMessageInfo

func (m *SetPaypwdIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SetPaypwdIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SetPaypwdIn) GetPaypwd() string {
	if m != nil {
		return m.Paypwd
	}
	return ""
}

func (m *SetPaypwdIn) GetVfcode() string {
	if m != nil {
		return m.Vfcode
	}
	return ""
}

type WsIn struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WsIn) Reset()         { *m = WsIn{} }
func (m *WsIn) String() string { return proto.CompactTextString(m) }
func (*WsIn) ProtoMessage()    {}
func (*WsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *WsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WsIn.Unmarshal(m, b)
}
func (m *WsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WsIn.Marshal(b, m, deterministic)
}
func (m *WsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WsIn.Merge(m, src)
}
func (m *WsIn) XXX_Size() int {
	return xxx_messageInfo_WsIn.Size(m)
}
func (m *WsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_WsIn.DiscardUnknown(m)
}

var xxx_messageInfo_WsIn proto.InternalMessageInfo

func (m *WsIn) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CommonOut struct {
	Httpcode             int32    `protobuf:"varint,1,opt,name=httpcode,proto3" json:"httpcode,omitempty"`
	Innercode            int32    `protobuf:"varint,2,opt,name=innercode,proto3" json:"innercode,omitempty"`
	Clientmsg            string   `protobuf:"bytes,3,opt,name=clientmsg,proto3" json:"clientmsg,omitempty"`
	Innermsg             string   `protobuf:"bytes,4,opt,name=innermsg,proto3" json:"innermsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonOut) Reset()         { *m = CommonOut{} }
func (m *CommonOut) String() string { return proto.CompactTextString(m) }
func (*CommonOut) ProtoMessage()    {}
func (*CommonOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CommonOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonOut.Unmarshal(m, b)
}
func (m *CommonOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonOut.Marshal(b, m, deterministic)
}
func (m *CommonOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonOut.Merge(m, src)
}
func (m *CommonOut) XXX_Size() int {
	return xxx_messageInfo_CommonOut.Size(m)
}
func (m *CommonOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonOut.DiscardUnknown(m)
}

var xxx_messageInfo_CommonOut proto.InternalMessageInfo

func (m *CommonOut) GetHttpcode() int32 {
	if m != nil {
		return m.Httpcode
	}
	return 0
}

func (m *CommonOut) GetInnercode() int32 {
	if m != nil {
		return m.Innercode
	}
	return 0
}

func (m *CommonOut) GetClientmsg() string {
	if m != nil {
		return m.Clientmsg
	}
	return ""
}

func (m *CommonOut) GetInnermsg() string {
	if m != nil {
		return m.Innermsg
	}
	return ""
}

func (m *CommonOut) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

//*******************************
type RegistIn struct {
	Invcodeagent         string   `protobuf:"bytes,1,opt,name=invcodeagent,proto3" json:"invcodeagent,omitempty"`
	Verifycode           string   `protobuf:"bytes,2,opt,name=verifycode,proto3" json:"verifycode,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Pwd                  string   `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ClientIp             string   `protobuf:"bytes,6,opt,name=ClientIp,proto3" json:"ClientIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistIn) Reset()         { *m = RegistIn{} }
func (m *RegistIn) String() string { return proto.CompactTextString(m) }
func (*RegistIn) ProtoMessage()    {}
func (*RegistIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegistIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistIn.Unmarshal(m, b)
}
func (m *RegistIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistIn.Marshal(b, m, deterministic)
}
func (m *RegistIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistIn.Merge(m, src)
}
func (m *RegistIn) XXX_Size() int {
	return xxx_messageInfo_RegistIn.Size(m)
}
func (m *RegistIn) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistIn.DiscardUnknown(m)
}

var xxx_messageInfo_RegistIn proto.InternalMessageInfo

func (m *RegistIn) GetInvcodeagent() string {
	if m != nil {
		return m.Invcodeagent
	}
	return ""
}

func (m *RegistIn) GetVerifycode() string {
	if m != nil {
		return m.Verifycode
	}
	return ""
}

func (m *RegistIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegistIn) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegistIn) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegistIn) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

//*******************************
type LoginIn struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Mobidecode           string   `protobuf:"bytes,2,opt,name=mobidecode,proto3" json:"mobidecode,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	ClientIp             string   `protobuf:"bytes,4,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginIn) Reset()         { *m = LoginIn{} }
func (m *LoginIn) String() string { return proto.CompactTextString(m) }
func (*LoginIn) ProtoMessage()    {}
func (*LoginIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LoginIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIn.Unmarshal(m, b)
}
func (m *LoginIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIn.Marshal(b, m, deterministic)
}
func (m *LoginIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIn.Merge(m, src)
}
func (m *LoginIn) XXX_Size() int {
	return xxx_messageInfo_LoginIn.Size(m)
}
func (m *LoginIn) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIn.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIn proto.InternalMessageInfo

func (m *LoginIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginIn) GetMobidecode() string {
	if m != nil {
		return m.Mobidecode
	}
	return ""
}

func (m *LoginIn) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *LoginIn) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *LoginIn) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

//*******************************
type ModifyBasicPwdIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Vfcode               string   `protobuf:"bytes,5,opt,name=vfcode,proto3" json:"vfcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyBasicPwdIn) Reset()         { *m = ModifyBasicPwdIn{} }
func (m *ModifyBasicPwdIn) String() string { return proto.CompactTextString(m) }
func (*ModifyBasicPwdIn) ProtoMessage()    {}
func (*ModifyBasicPwdIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ModifyBasicPwdIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyBasicPwdIn.Unmarshal(m, b)
}
func (m *ModifyBasicPwdIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyBasicPwdIn.Marshal(b, m, deterministic)
}
func (m *ModifyBasicPwdIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyBasicPwdIn.Merge(m, src)
}
func (m *ModifyBasicPwdIn) XXX_Size() int {
	return xxx_messageInfo_ModifyBasicPwdIn.Size(m)
}
func (m *ModifyBasicPwdIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyBasicPwdIn.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyBasicPwdIn proto.InternalMessageInfo

func (m *ModifyBasicPwdIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ModifyBasicPwdIn) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *ModifyBasicPwdIn) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ModifyBasicPwdIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ModifyBasicPwdIn) GetVfcode() string {
	if m != nil {
		return m.Vfcode
	}
	return ""
}

type ModifyLoginPwdIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Oldpwd               string   `protobuf:"bytes,3,opt,name=oldpwd,proto3" json:"oldpwd,omitempty"`
	Newpwd               string   `protobuf:"bytes,4,opt,name=newpwd,proto3" json:"newpwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyLoginPwdIn) Reset()         { *m = ModifyLoginPwdIn{} }
func (m *ModifyLoginPwdIn) String() string { return proto.CompactTextString(m) }
func (*ModifyLoginPwdIn) ProtoMessage()    {}
func (*ModifyLoginPwdIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ModifyLoginPwdIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyLoginPwdIn.Unmarshal(m, b)
}
func (m *ModifyLoginPwdIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyLoginPwdIn.Marshal(b, m, deterministic)
}
func (m *ModifyLoginPwdIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyLoginPwdIn.Merge(m, src)
}
func (m *ModifyLoginPwdIn) XXX_Size() int {
	return xxx_messageInfo_ModifyLoginPwdIn.Size(m)
}
func (m *ModifyLoginPwdIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyLoginPwdIn.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyLoginPwdIn proto.InternalMessageInfo

func (m *ModifyLoginPwdIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ModifyLoginPwdIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ModifyLoginPwdIn) GetOldpwd() string {
	if m != nil {
		return m.Oldpwd
	}
	return ""
}

func (m *ModifyLoginPwdIn) GetNewpwd() string {
	if m != nil {
		return m.Newpwd
	}
	return ""
}

type ModifyPayPwdIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Newpwd               string   `protobuf:"bytes,3,opt,name=newpwd,proto3" json:"newpwd,omitempty"`
	Vfcode               string   `protobuf:"bytes,4,opt,name=vfcode,proto3" json:"vfcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPayPwdIn) Reset()         { *m = ModifyPayPwdIn{} }
func (m *ModifyPayPwdIn) String() string { return proto.CompactTextString(m) }
func (*ModifyPayPwdIn) ProtoMessage()    {}
func (*ModifyPayPwdIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *ModifyPayPwdIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPayPwdIn.Unmarshal(m, b)
}
func (m *ModifyPayPwdIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPayPwdIn.Marshal(b, m, deterministic)
}
func (m *ModifyPayPwdIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPayPwdIn.Merge(m, src)
}
func (m *ModifyPayPwdIn) XXX_Size() int {
	return xxx_messageInfo_ModifyPayPwdIn.Size(m)
}
func (m *ModifyPayPwdIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPayPwdIn.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPayPwdIn proto.InternalMessageInfo

func (m *ModifyPayPwdIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ModifyPayPwdIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ModifyPayPwdIn) GetNewpwd() string {
	if m != nil {
		return m.Newpwd
	}
	return ""
}

func (m *ModifyPayPwdIn) GetVfcode() string {
	if m != nil {
		return m.Vfcode
	}
	return ""
}

//*******************************
type GetMemberUserAgentIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMemberUserAgentIn) Reset()         { *m = GetMemberUserAgentIn{} }
func (m *GetMemberUserAgentIn) String() string { return proto.CompactTextString(m) }
func (*GetMemberUserAgentIn) ProtoMessage()    {}
func (*GetMemberUserAgentIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetMemberUserAgentIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMemberUserAgentIn.Unmarshal(m, b)
}
func (m *GetMemberUserAgentIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMemberUserAgentIn.Marshal(b, m, deterministic)
}
func (m *GetMemberUserAgentIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMemberUserAgentIn.Merge(m, src)
}
func (m *GetMemberUserAgentIn) XXX_Size() int {
	return xxx_messageInfo_GetMemberUserAgentIn.Size(m)
}
func (m *GetMemberUserAgentIn) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMemberUserAgentIn.DiscardUnknown(m)
}

var xxx_messageInfo_GetMemberUserAgentIn proto.InternalMessageInfo

func (m *GetMemberUserAgentIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

//*******************************
type ConnectUsIn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectUsIn) Reset()         { *m = ConnectUsIn{} }
func (m *ConnectUsIn) String() string { return proto.CompactTextString(m) }
func (*ConnectUsIn) ProtoMessage()    {}
func (*ConnectUsIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *ConnectUsIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectUsIn.Unmarshal(m, b)
}
func (m *ConnectUsIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectUsIn.Marshal(b, m, deterministic)
}
func (m *ConnectUsIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectUsIn.Merge(m, src)
}
func (m *ConnectUsIn) XXX_Size() int {
	return xxx_messageInfo_ConnectUsIn.Size(m)
}
func (m *ConnectUsIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectUsIn.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectUsIn proto.InternalMessageInfo

//*******************************
type ExchangeRateIn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeRateIn) Reset()         { *m = ExchangeRateIn{} }
func (m *ExchangeRateIn) String() string { return proto.CompactTextString(m) }
func (*ExchangeRateIn) ProtoMessage()    {}
func (*ExchangeRateIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ExchangeRateIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRateIn.Unmarshal(m, b)
}
func (m *ExchangeRateIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRateIn.Marshal(b, m, deterministic)
}
func (m *ExchangeRateIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRateIn.Merge(m, src)
}
func (m *ExchangeRateIn) XXX_Size() int {
	return xxx_messageInfo_ExchangeRateIn.Size(m)
}
func (m *ExchangeRateIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRateIn.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRateIn proto.InternalMessageInfo

type MemberDepositIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	InvcodeSelf          string   `protobuf:"bytes,3,opt,name=invcode_self,json=invcodeSelf,proto3" json:"invcode_self,omitempty"`
	InvcodeAgent         string   `protobuf:"bytes,4,opt,name=invcode_agent,json=invcodeAgent,proto3" json:"invcode_agent,omitempty"`
	DepositType          int32    `protobuf:"varint,5,opt,name=deposit_type,json=depositType,proto3" json:"deposit_type,omitempty"`
	DepositName          string   `protobuf:"bytes,6,opt,name=deposit_name,json=depositName,proto3" json:"deposit_name,omitempty"`
	DepositNum           float32  `protobuf:"fixed32,7,opt,name=deposit_num,json=depositNum,proto3" json:"deposit_num,omitempty"`
	Addressin            string   `protobuf:"bytes,8,opt,name=addressin,proto3" json:"addressin,omitempty"`
	Addressout           string   `protobuf:"bytes,9,opt,name=addressout,proto3" json:"addressout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDepositIn) Reset()         { *m = MemberDepositIn{} }
func (m *MemberDepositIn) String() string { return proto.CompactTextString(m) }
func (*MemberDepositIn) ProtoMessage()    {}
func (*MemberDepositIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *MemberDepositIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDepositIn.Unmarshal(m, b)
}
func (m *MemberDepositIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDepositIn.Marshal(b, m, deterministic)
}
func (m *MemberDepositIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDepositIn.Merge(m, src)
}
func (m *MemberDepositIn) XXX_Size() int {
	return xxx_messageInfo_MemberDepositIn.Size(m)
}
func (m *MemberDepositIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDepositIn.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDepositIn proto.InternalMessageInfo

func (m *MemberDepositIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MemberDepositIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberDepositIn) GetInvcodeSelf() string {
	if m != nil {
		return m.InvcodeSelf
	}
	return ""
}

func (m *MemberDepositIn) GetInvcodeAgent() string {
	if m != nil {
		return m.InvcodeAgent
	}
	return ""
}

func (m *MemberDepositIn) GetDepositType() int32 {
	if m != nil {
		return m.DepositType
	}
	return 0
}

func (m *MemberDepositIn) GetDepositName() string {
	if m != nil {
		return m.DepositName
	}
	return ""
}

func (m *MemberDepositIn) GetDepositNum() float32 {
	if m != nil {
		return m.DepositNum
	}
	return 0
}

func (m *MemberDepositIn) GetAddressin() string {
	if m != nil {
		return m.Addressin
	}
	return ""
}

func (m *MemberDepositIn) GetAddressout() string {
	if m != nil {
		return m.Addressout
	}
	return ""
}

type OnlinePayIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SrcId                string   `protobuf:"bytes,3,opt,name=srcId,proto3" json:"srcId,omitempty"`
	InvcodeSelf          string   `protobuf:"bytes,4,opt,name=invcode_self,json=invcodeSelf,proto3" json:"invcode_self,omitempty"`
	InvcodeAgent         string   `protobuf:"bytes,5,opt,name=invcode_agent,json=invcodeAgent,proto3" json:"invcode_agent,omitempty"`
	DepositType          int32    `protobuf:"varint,6,opt,name=deposit_type,json=depositType,proto3" json:"deposit_type,omitempty"`
	DepositName          string   `protobuf:"bytes,7,opt,name=deposit_name,json=depositName,proto3" json:"deposit_name,omitempty"`
	DepositNum           float32  `protobuf:"fixed32,8,opt,name=deposit_num,json=depositNum,proto3" json:"deposit_num,omitempty"`
	Addressin            string   `protobuf:"bytes,9,opt,name=addressin,proto3" json:"addressin,omitempty"`
	Addressout           string   `protobuf:"bytes,10,opt,name=addressout,proto3" json:"addressout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlinePayIn) Reset()         { *m = OnlinePayIn{} }
func (m *OnlinePayIn) String() string { return proto.CompactTextString(m) }
func (*OnlinePayIn) ProtoMessage()    {}
func (*OnlinePayIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *OnlinePayIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlinePayIn.Unmarshal(m, b)
}
func (m *OnlinePayIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlinePayIn.Marshal(b, m, deterministic)
}
func (m *OnlinePayIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlinePayIn.Merge(m, src)
}
func (m *OnlinePayIn) XXX_Size() int {
	return xxx_messageInfo_OnlinePayIn.Size(m)
}
func (m *OnlinePayIn) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlinePayIn.DiscardUnknown(m)
}

var xxx_messageInfo_OnlinePayIn proto.InternalMessageInfo

func (m *OnlinePayIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *OnlinePayIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OnlinePayIn) GetSrcId() string {
	if m != nil {
		return m.SrcId
	}
	return ""
}

func (m *OnlinePayIn) GetInvcodeSelf() string {
	if m != nil {
		return m.InvcodeSelf
	}
	return ""
}

func (m *OnlinePayIn) GetInvcodeAgent() string {
	if m != nil {
		return m.InvcodeAgent
	}
	return ""
}

func (m *OnlinePayIn) GetDepositType() int32 {
	if m != nil {
		return m.DepositType
	}
	return 0
}

func (m *OnlinePayIn) GetDepositName() string {
	if m != nil {
		return m.DepositName
	}
	return ""
}

func (m *OnlinePayIn) GetDepositNum() float32 {
	if m != nil {
		return m.DepositNum
	}
	return 0
}

func (m *OnlinePayIn) GetAddressin() string {
	if m != nil {
		return m.Addressin
	}
	return ""
}

func (m *OnlinePayIn) GetAddressout() string {
	if m != nil {
		return m.Addressout
	}
	return ""
}

type MemberDepositLogIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	TypeName             string   `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeTag              int32    `protobuf:"varint,4,opt,name=type_tag,json=typeTag,proto3" json:"type_tag,omitempty"`
	PageSize             int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Index                int32    `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDepositLogIn) Reset()         { *m = MemberDepositLogIn{} }
func (m *MemberDepositLogIn) String() string { return proto.CompactTextString(m) }
func (*MemberDepositLogIn) ProtoMessage()    {}
func (*MemberDepositLogIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *MemberDepositLogIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDepositLogIn.Unmarshal(m, b)
}
func (m *MemberDepositLogIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDepositLogIn.Marshal(b, m, deterministic)
}
func (m *MemberDepositLogIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDepositLogIn.Merge(m, src)
}
func (m *MemberDepositLogIn) XXX_Size() int {
	return xxx_messageInfo_MemberDepositLogIn.Size(m)
}
func (m *MemberDepositLogIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDepositLogIn.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDepositLogIn proto.InternalMessageInfo

func (m *MemberDepositLogIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MemberDepositLogIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MemberDepositLogIn) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *MemberDepositLogIn) GetTypeTag() int32 {
	if m != nil {
		return m.TypeTag
	}
	return 0
}

func (m *MemberDepositLogIn) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *MemberDepositLogIn) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type MemerClassSetIn struct {
	Money1               float32  `protobuf:"fixed32,1,opt,name=money1,proto3" json:"money1,omitempty"`
	Money2               float32  `protobuf:"fixed32,2,opt,name=money2,proto3" json:"money2,omitempty"`
	Money3               float32  `protobuf:"fixed32,3,opt,name=money3,proto3" json:"money3,omitempty"`
	Money4               float32  `protobuf:"fixed32,4,opt,name=money4,proto3" json:"money4,omitempty"`
	Money5               float32  `protobuf:"fixed32,5,opt,name=money5,proto3" json:"money5,omitempty"`
	Tag1                 int32    `protobuf:"varint,6,opt,name=tag1,proto3" json:"tag1,omitempty"`
	Tag2                 int32    `protobuf:"varint,7,opt,name=tag2,proto3" json:"tag2,omitempty"`
	Tag3                 int32    `protobuf:"varint,8,opt,name=tag3,proto3" json:"tag3,omitempty"`
	Tag4                 int32    `protobuf:"varint,9,opt,name=tag4,proto3" json:"tag4,omitempty"`
	Tag5                 int32    `protobuf:"varint,10,opt,name=tag5,proto3" json:"tag5,omitempty"`
	Tagex1               string   `protobuf:"bytes,11,opt,name=tagex1,proto3" json:"tagex1,omitempty"`
	Tagex2               string   `protobuf:"bytes,12,opt,name=tagex2,proto3" json:"tagex2,omitempty"`
	Tagex3               string   `protobuf:"bytes,13,opt,name=tagex3,proto3" json:"tagex3,omitempty"`
	Tagex4               string   `protobuf:"bytes,14,opt,name=tagex4,proto3" json:"tagex4,omitempty"`
	Tagex5               string   `protobuf:"bytes,15,opt,name=tagex5,proto3" json:"tagex5,omitempty"`
	Memname1             string   `protobuf:"bytes,16,opt,name=memname1,proto3" json:"memname1,omitempty"`
	Memname2             string   `protobuf:"bytes,17,opt,name=memname2,proto3" json:"memname2,omitempty"`
	Memname3             string   `protobuf:"bytes,18,opt,name=memname3,proto3" json:"memname3,omitempty"`
	Memname4             string   `protobuf:"bytes,19,opt,name=memname4,proto3" json:"memname4,omitempty"`
	Memname5             string   `protobuf:"bytes,20,opt,name=memname5,proto3" json:"memname5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemerClassSetIn) Reset()         { *m = MemerClassSetIn{} }
func (m *MemerClassSetIn) String() string { return proto.CompactTextString(m) }
func (*MemerClassSetIn) ProtoMessage()    {}
func (*MemerClassSetIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *MemerClassSetIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemerClassSetIn.Unmarshal(m, b)
}
func (m *MemerClassSetIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemerClassSetIn.Marshal(b, m, deterministic)
}
func (m *MemerClassSetIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemerClassSetIn.Merge(m, src)
}
func (m *MemerClassSetIn) XXX_Size() int {
	return xxx_messageInfo_MemerClassSetIn.Size(m)
}
func (m *MemerClassSetIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MemerClassSetIn.DiscardUnknown(m)
}

var xxx_messageInfo_MemerClassSetIn proto.InternalMessageInfo

func (m *MemerClassSetIn) GetMoney1() float32 {
	if m != nil {
		return m.Money1
	}
	return 0
}

func (m *MemerClassSetIn) GetMoney2() float32 {
	if m != nil {
		return m.Money2
	}
	return 0
}

func (m *MemerClassSetIn) GetMoney3() float32 {
	if m != nil {
		return m.Money3
	}
	return 0
}

func (m *MemerClassSetIn) GetMoney4() float32 {
	if m != nil {
		return m.Money4
	}
	return 0
}

func (m *MemerClassSetIn) GetMoney5() float32 {
	if m != nil {
		return m.Money5
	}
	return 0
}

func (m *MemerClassSetIn) GetTag1() int32 {
	if m != nil {
		return m.Tag1
	}
	return 0
}

func (m *MemerClassSetIn) GetTag2() int32 {
	if m != nil {
		return m.Tag2
	}
	return 0
}

func (m *MemerClassSetIn) GetTag3() int32 {
	if m != nil {
		return m.Tag3
	}
	return 0
}

func (m *MemerClassSetIn) GetTag4() int32 {
	if m != nil {
		return m.Tag4
	}
	return 0
}

func (m *MemerClassSetIn) GetTag5() int32 {
	if m != nil {
		return m.Tag5
	}
	return 0
}

func (m *MemerClassSetIn) GetTagex1() string {
	if m != nil {
		return m.Tagex1
	}
	return ""
}

func (m *MemerClassSetIn) GetTagex2() string {
	if m != nil {
		return m.Tagex2
	}
	return ""
}

func (m *MemerClassSetIn) GetTagex3() string {
	if m != nil {
		return m.Tagex3
	}
	return ""
}

func (m *MemerClassSetIn) GetTagex4() string {
	if m != nil {
		return m.Tagex4
	}
	return ""
}

func (m *MemerClassSetIn) GetTagex5() string {
	if m != nil {
		return m.Tagex5
	}
	return ""
}

func (m *MemerClassSetIn) GetMemname1() string {
	if m != nil {
		return m.Memname1
	}
	return ""
}

func (m *MemerClassSetIn) GetMemname2() string {
	if m != nil {
		return m.Memname2
	}
	return ""
}

func (m *MemerClassSetIn) GetMemname3() string {
	if m != nil {
		return m.Memname3
	}
	return ""
}

func (m *MemerClassSetIn) GetMemname4() string {
	if m != nil {
		return m.Memname4
	}
	return ""
}

func (m *MemerClassSetIn) GetMemname5() string {
	if m != nil {
		return m.Memname5
	}
	return ""
}

type AgentClassSetIn struct {
	Money1               float32  `protobuf:"fixed32,1,opt,name=money1,proto3" json:"money1,omitempty"`
	Money2               float32  `protobuf:"fixed32,2,opt,name=money2,proto3" json:"money2,omitempty"`
	Money3               float32  `protobuf:"fixed32,3,opt,name=money3,proto3" json:"money3,omitempty"`
	Money4               float32  `protobuf:"fixed32,4,opt,name=money4,proto3" json:"money4,omitempty"`
	Money5               float32  `protobuf:"fixed32,5,opt,name=money5,proto3" json:"money5,omitempty"`
	Tag1                 int32    `protobuf:"varint,6,opt,name=tag1,proto3" json:"tag1,omitempty"`
	Tag2                 int32    `protobuf:"varint,7,opt,name=tag2,proto3" json:"tag2,omitempty"`
	Tag3                 int32    `protobuf:"varint,8,opt,name=tag3,proto3" json:"tag3,omitempty"`
	Tag4                 int32    `protobuf:"varint,9,opt,name=tag4,proto3" json:"tag4,omitempty"`
	Tag5                 int32    `protobuf:"varint,10,opt,name=tag5,proto3" json:"tag5,omitempty"`
	Tagex1               string   `protobuf:"bytes,11,opt,name=tagex1,proto3" json:"tagex1,omitempty"`
	Tagex2               string   `protobuf:"bytes,12,opt,name=tagex2,proto3" json:"tagex2,omitempty"`
	Tagex3               string   `protobuf:"bytes,13,opt,name=tagex3,proto3" json:"tagex3,omitempty"`
	Tagex4               string   `protobuf:"bytes,14,opt,name=tagex4,proto3" json:"tagex4,omitempty"`
	Tagex5               string   `protobuf:"bytes,15,opt,name=tagex5,proto3" json:"tagex5,omitempty"`
	Agentname1           string   `protobuf:"bytes,16,opt,name=agentname1,proto3" json:"agentname1,omitempty"`
	Agentname2           string   `protobuf:"bytes,17,opt,name=agentname2,proto3" json:"agentname2,omitempty"`
	Agentname3           string   `protobuf:"bytes,18,opt,name=agentname3,proto3" json:"agentname3,omitempty"`
	Agentname4           string   `protobuf:"bytes,19,opt,name=agentname4,proto3" json:"agentname4,omitempty"`
	Agentname5           string   `protobuf:"bytes,20,opt,name=agentname5,proto3" json:"agentname5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentClassSetIn) Reset()         { *m = AgentClassSetIn{} }
func (m *AgentClassSetIn) String() string { return proto.CompactTextString(m) }
func (*AgentClassSetIn) ProtoMessage()    {}
func (*AgentClassSetIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *AgentClassSetIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentClassSetIn.Unmarshal(m, b)
}
func (m *AgentClassSetIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentClassSetIn.Marshal(b, m, deterministic)
}
func (m *AgentClassSetIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentClassSetIn.Merge(m, src)
}
func (m *AgentClassSetIn) XXX_Size() int {
	return xxx_messageInfo_AgentClassSetIn.Size(m)
}
func (m *AgentClassSetIn) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentClassSetIn.DiscardUnknown(m)
}

var xxx_messageInfo_AgentClassSetIn proto.InternalMessageInfo

func (m *AgentClassSetIn) GetMoney1() float32 {
	if m != nil {
		return m.Money1
	}
	return 0
}

func (m *AgentClassSetIn) GetMoney2() float32 {
	if m != nil {
		return m.Money2
	}
	return 0
}

func (m *AgentClassSetIn) GetMoney3() float32 {
	if m != nil {
		return m.Money3
	}
	return 0
}

func (m *AgentClassSetIn) GetMoney4() float32 {
	if m != nil {
		return m.Money4
	}
	return 0
}

func (m *AgentClassSetIn) GetMoney5() float32 {
	if m != nil {
		return m.Money5
	}
	return 0
}

func (m *AgentClassSetIn) GetTag1() int32 {
	if m != nil {
		return m.Tag1
	}
	return 0
}

func (m *AgentClassSetIn) GetTag2() int32 {
	if m != nil {
		return m.Tag2
	}
	return 0
}

func (m *AgentClassSetIn) GetTag3() int32 {
	if m != nil {
		return m.Tag3
	}
	return 0
}

func (m *AgentClassSetIn) GetTag4() int32 {
	if m != nil {
		return m.Tag4
	}
	return 0
}

func (m *AgentClassSetIn) GetTag5() int32 {
	if m != nil {
		return m.Tag5
	}
	return 0
}

func (m *AgentClassSetIn) GetTagex1() string {
	if m != nil {
		return m.Tagex1
	}
	return ""
}

func (m *AgentClassSetIn) GetTagex2() string {
	if m != nil {
		return m.Tagex2
	}
	return ""
}

func (m *AgentClassSetIn) GetTagex3() string {
	if m != nil {
		return m.Tagex3
	}
	return ""
}

func (m *AgentClassSetIn) GetTagex4() string {
	if m != nil {
		return m.Tagex4
	}
	return ""
}

func (m *AgentClassSetIn) GetTagex5() string {
	if m != nil {
		return m.Tagex5
	}
	return ""
}

func (m *AgentClassSetIn) GetAgentname1() string {
	if m != nil {
		return m.Agentname1
	}
	return ""
}

func (m *AgentClassSetIn) GetAgentname2() string {
	if m != nil {
		return m.Agentname2
	}
	return ""
}

func (m *AgentClassSetIn) GetAgentname3() string {
	if m != nil {
		return m.Agentname3
	}
	return ""
}

func (m *AgentClassSetIn) GetAgentname4() string {
	if m != nil {
		return m.Agentname4
	}
	return ""
}

func (m *AgentClassSetIn) GetAgentname5() string {
	if m != nil {
		return m.Agentname5
	}
	return ""
}

type MemberUsdtRechargeIn struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUsdtRechargeIn) Reset()         { *m = MemberUsdtRechargeIn{} }
func (m *MemberUsdtRechargeIn) String() string { return proto.CompactTextString(m) }
func (*MemberUsdtRechargeIn) ProtoMessage()    {}
func (*MemberUsdtRechargeIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *MemberUsdtRechargeIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUsdtRechargeIn.Unmarshal(m, b)
}
func (m *MemberUsdtRechargeIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUsdtRechargeIn.Marshal(b, m, deterministic)
}
func (m *MemberUsdtRechargeIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUsdtRechargeIn.Merge(m, src)
}
func (m *MemberUsdtRechargeIn) XXX_Size() int {
	return xxx_messageInfo_MemberUsdtRechargeIn.Size(m)
}
func (m *MemberUsdtRechargeIn) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUsdtRechargeIn.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUsdtRechargeIn proto.InternalMessageInfo

func (m *MemberUsdtRechargeIn) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *MemberUsdtRechargeIn) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*SetPaypwdIn)(nil), "ds.srv.user.SetPaypwdIn")
	proto.RegisterType((*WsIn)(nil), "ds.srv.user.WsIn")
	proto.RegisterType((*CommonOut)(nil), "ds.srv.user.CommonOut")
	proto.RegisterType((*RegistIn)(nil), "ds.srv.user.RegistIn")
	proto.RegisterType((*LoginIn)(nil), "ds.srv.user.LoginIn")
	proto.RegisterType((*ModifyBasicPwdIn)(nil), "ds.srv.user.ModifyBasicPwdIn")
	proto.RegisterType((*ModifyLoginPwdIn)(nil), "ds.srv.user.ModifyLoginPwdIn")
	proto.RegisterType((*ModifyPayPwdIn)(nil), "ds.srv.user.ModifyPayPwdIn")
	proto.RegisterType((*GetMemberUserAgentIn)(nil), "ds.srv.user.GetMemberUserAgentIn")
	proto.RegisterType((*ConnectUsIn)(nil), "ds.srv.user.ConnectUsIn")
	proto.RegisterType((*ExchangeRateIn)(nil), "ds.srv.user.ExchangeRateIn")
	proto.RegisterType((*MemberDepositIn)(nil), "ds.srv.user.MemberDepositIn")
	proto.RegisterType((*OnlinePayIn)(nil), "ds.srv.user.OnlinePayIn")
	proto.RegisterType((*MemberDepositLogIn)(nil), "ds.srv.user.MemberDepositLogIn")
	proto.RegisterType((*MemerClassSetIn)(nil), "ds.srv.user.MemerClassSetIn")
	proto.RegisterType((*AgentClassSetIn)(nil), "ds.srv.user.AgentClassSetIn")
	proto.RegisterType((*MemberUsdtRechargeIn)(nil), "ds.srv.user.MemberUsdtRechargeIn")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 1180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcb, 0x6e, 0x1b, 0x37,
	0x14, 0xed, 0xe8, 0x65, 0xe9, 0xca, 0x0f, 0x85, 0x75, 0x03, 0x36, 0x49, 0x13, 0x67, 0xba, 0x31,
	0xba, 0x30, 0x62, 0x3d, 0x50, 0x64, 0x51, 0x14, 0x8d, 0x1b, 0x04, 0x02, 0xe2, 0xc6, 0x1d, 0x25,
	0xc8, 0xd2, 0x18, 0x6b, 0xe8, 0xf1, 0xa0, 0x1a, 0x8e, 0x30, 0x43, 0x39, 0x56, 0x96, 0x2d, 0xfa,
	0x05, 0xfd, 0x8b, 0x66, 0xd3, 0x0f, 0xe8, 0x4f, 0xf5, 0x0f, 0x0a, 0x3e, 0x45, 0xca, 0xd6, 0xf8,
	0x01, 0x74, 0xd7, 0x1d, 0xef, 0xb9, 0x9c, 0xcb, 0xc3, 0x7b, 0x2f, 0xc9, 0x23, 0x01, 0xcc, 0x0a,
	0x92, 0xef, 0x4d, 0xf3, 0x8c, 0x65, 0xa8, 0x1d, 0x15, 0x7b, 0x45, 0x7e, 0xbe, 0xc7, 0x21, 0x3f,
	0x81, 0xf6, 0x88, 0xb0, 0xa3, 0x70, 0x3e, 0xfd, 0x10, 0x0d, 0x29, 0x42, 0x50, 0x9b, 0xcd, 0x92,
	0x08, 0x7b, 0x3b, 0xde, 0x6e, 0x2b, 0x10, 0x63, 0x74, 0x1f, 0x1a, 0x69, 0x76, 0x92, 0x4c, 0x08,
	0xae, 0x08, 0x54, 0x59, 0x1c, 0x9f, 0x8a, 0xef, 0x70, 0x55, 0xe2, 0xd2, 0xe2, 0xf8, 0xf9, 0xe9,
	0x38, 0x8b, 0x08, 0xae, 0x49, 0x5c, 0x5a, 0x3e, 0x86, 0xda, 0xfb, 0x62, 0x48, 0x51, 0x07, 0xaa,
	0x69, 0x11, 0xab, 0x25, 0xf8, 0xd0, 0xff, 0xc3, 0x83, 0xd6, 0x41, 0x96, 0xa6, 0x19, 0x7d, 0x33,
	0x63, 0xe8, 0x01, 0x34, 0xcf, 0x18, 0x9b, 0x8a, 0x08, 0x7c, 0x52, 0x3d, 0x30, 0x36, 0x7a, 0x04,
	0xad, 0x84, 0x52, 0x92, 0x0b, 0x67, 0x45, 0x38, 0x17, 0x00, 0xf7, 0x8e, 0x27, 0x09, 0xa1, 0x8c,
	0xc7, 0x97, 0xa4, 0x16, 0x00, 0x8f, 0x2b, 0xa6, 0x72, 0xa7, 0x64, 0x66, 0x6c, 0xbe, 0xef, 0x28,
	0x64, 0x21, 0xae, 0xef, 0x78, 0xbb, 0xeb, 0x81, 0x18, 0xfb, 0x7f, 0x79, 0xd0, 0x0c, 0x48, 0x9c,
	0x14, 0x6c, 0x48, 0x91, 0x0f, 0xeb, 0x09, 0x3d, 0xe7, 0xab, 0x84, 0x31, 0xa1, 0x4c, 0xb1, 0x77,
	0x30, 0xf4, 0x18, 0xe0, 0x9c, 0xe4, 0xc9, 0xe9, 0xdc, 0xb0, 0x6b, 0x05, 0x16, 0x62, 0x25, 0xb2,
	0xea, 0x24, 0xb2, 0x03, 0x55, 0x9e, 0x45, 0xc9, 0x89, 0x0f, 0x39, 0x55, 0x9a, 0x8c, 0x7f, 0xa1,
	0x61, 0x4a, 0x04, 0xa5, 0x56, 0x60, 0x6c, 0xee, 0x3b, 0x10, 0x7b, 0x1a, 0x4e, 0x71, 0x43, 0xfa,
	0xb4, 0xed, 0xff, 0xe6, 0xc1, 0xda, 0xeb, 0x2c, 0x4e, 0xe8, 0x90, 0x5a, 0xab, 0x79, 0xce, 0x6a,
	0x8f, 0x01, 0xf8, 0x28, 0x22, 0x36, 0xcb, 0x05, 0xa2, 0xd9, 0x54, 0x1d, 0x36, 0x63, 0xbd, 0xa2,
	0x4a, 0x9c, 0xb6, 0x79, 0xe2, 0xd8, 0x7c, 0xaa, 0x59, 0x8a, 0xb1, 0xff, 0xab, 0x07, 0x9d, 0xc3,
	0x2c, 0x4a, 0x4e, 0xe7, 0x2f, 0xc2, 0x22, 0x19, 0x1f, 0xad, 0xec, 0xac, 0x0e, 0x54, 0x59, 0x18,
	0x2b, 0x0e, 0x7c, 0x88, 0x30, 0xac, 0x8d, 0x33, 0xca, 0x78, 0x86, 0x25, 0x01, 0x6d, 0x5a, 0xdb,
	0xa9, 0x2d, 0x77, 0xa1, 0xea, 0xb6, 0xba, 0xd3, 0x6d, 0x54, 0x73, 0x10, 0xf9, 0x38, 0xba, 0x4b,
	0x77, 0x67, 0x93, 0xc8, 0xea, 0x6e, 0x69, 0x71, 0x9c, 0x92, 0x0f, 0x8b, 0x7a, 0x29, 0xcb, 0x9f,
	0xc0, 0xa6, 0x5c, 0xef, 0x28, 0x9c, 0xdf, 0x69, 0x35, 0x15, 0xb5, 0x6a, 0x47, 0x5d, 0x79, 0x96,
	0xbe, 0x81, 0xed, 0x57, 0x84, 0x1d, 0x92, 0xf4, 0x84, 0xe4, 0xef, 0x0a, 0x92, 0xff, 0xc0, 0x1b,
	0xf0, 0xea, 0x35, 0xfd, 0x0d, 0x68, 0x1f, 0x64, 0x94, 0x92, 0x31, 0x7b, 0x57, 0x0c, 0xa9, 0xdf,
	0x81, 0xcd, 0x97, 0x17, 0xe3, 0xb3, 0x90, 0xc6, 0x24, 0x08, 0x19, 0x19, 0x52, 0xff, 0xcf, 0x0a,
	0x6c, 0xc9, 0x50, 0x3f, 0x92, 0x69, 0x56, 0x24, 0xec, 0x96, 0xe4, 0x9f, 0x9a, 0xb3, 0x71, 0x5c,
	0x90, 0xc9, 0xa9, 0xda, 0x42, 0x5b, 0x61, 0x23, 0x32, 0x39, 0x45, 0x5f, 0xc3, 0x86, 0x9e, 0x22,
	0xcf, 0x4f, 0xcd, 0x39, 0x3f, 0x82, 0x3e, 0x8f, 0x13, 0x49, 0x02, 0xc7, 0xa6, 0xa7, 0xea, 0x41,
	0x5b, 0x61, 0x6f, 0xe7, 0x53, 0x62, 0x4f, 0x11, 0x87, 0x43, 0x1e, 0x00, 0x3d, 0xe5, 0x27, 0x7e,
	0x3e, 0x9e, 0x40, 0xdb, 0x4c, 0x99, 0xa5, 0x78, 0x6d, 0xc7, 0xdb, 0xad, 0x04, 0xa0, 0x67, 0xcc,
	0x52, 0x7e, 0x4b, 0x84, 0x51, 0x94, 0x93, 0xa2, 0x48, 0x28, 0x6e, 0xca, 0x5b, 0xc2, 0x00, 0xfc,
	0x78, 0x28, 0x23, 0x9b, 0x31, 0xdc, 0x92, 0xc7, 0x63, 0x81, 0xf8, 0x7f, 0x57, 0xa0, 0xfd, 0x86,
	0x4e, 0x12, 0x4a, 0x8e, 0xc2, 0xf9, 0x2d, 0x13, 0xb5, 0x0d, 0xf5, 0x22, 0x1f, 0x0f, 0x75, 0x91,
	0xa5, 0x71, 0x29, 0x7d, 0xb5, 0x1b, 0xa4, 0xaf, 0x7e, 0x83, 0xf4, 0x35, 0xae, 0x4f, 0xdf, 0xda,
	0xb5, 0xe9, 0x6b, 0x96, 0xa7, 0xaf, 0x55, 0x9e, 0x3e, 0xb8, 0x94, 0xbe, 0x4f, 0x1e, 0x20, 0xa7,
	0xd7, 0x5e, 0x67, 0xf1, 0x2d, 0xb3, 0xf8, 0x10, 0x5a, 0x7c, 0x7f, 0x72, 0x07, 0x32, 0x93, 0x4d,
	0x0e, 0x08, 0xfa, 0x5f, 0x82, 0x18, 0x1f, 0xf3, 0x7b, 0xa5, 0x26, 0x12, 0xb0, 0xc6, 0xed, 0xb7,
	0x61, 0xcc, 0xbf, 0x9b, 0x86, 0x31, 0x39, 0x2e, 0x92, 0x8f, 0xba, 0xb7, 0x9a, 0x1c, 0x18, 0x25,
	0x1f, 0x45, 0x69, 0x12, 0x1a, 0x91, 0x0b, 0x95, 0x35, 0x69, 0xf8, 0xff, 0x54, 0xc5, 0xc9, 0x20,
	0xf9, 0xc1, 0x24, 0x2c, 0x8a, 0x11, 0x61, 0xfa, 0x5e, 0xa5, 0x64, 0xbe, 0x2f, 0xc8, 0x56, 0x02,
	0x65, 0x19, 0xbc, 0x2b, 0xe8, 0x6a, 0xbc, 0x6b, 0xf0, 0x9e, 0xe0, 0xaa, 0xf1, 0x9e, 0xc1, 0xfb,
	0x82, 0xa7, 0xc6, 0xfb, 0x06, 0x1f, 0x08, 0x8e, 0x1a, 0x1f, 0x88, 0x9b, 0x36, 0x8c, 0xf7, 0x15,
	0x41, 0x31, 0x56, 0x58, 0x57, 0xd4, 0x51, 0x62, 0x5d, 0x85, 0xf5, 0x44, 0xe5, 0x24, 0xd6, 0x53,
	0x58, 0x5f, 0x94, 0x4b, 0x62, 0x7d, 0x85, 0x0d, 0x44, 0x8d, 0x24, 0x36, 0xe0, 0x6b, 0xb3, 0x30,
	0x26, 0x17, 0xfb, 0xb8, 0x2d, 0x53, 0x2e, 0x2d, 0x83, 0x77, 0xf1, 0xba, 0x85, 0x77, 0x0d, 0xde,
	0xc3, 0x1b, 0x16, 0xde, 0x33, 0x78, 0x1f, 0x6f, 0x5a, 0x78, 0xdf, 0xe0, 0x03, 0xbc, 0x65, 0xe1,
	0x03, 0xfe, 0xc2, 0xa4, 0x24, 0xe5, 0x05, 0xdd, 0xc7, 0x1d, 0x59, 0x51, 0x6d, 0x5b, 0xbe, 0x2e,
	0xbe, 0xe7, 0xf8, 0xba, 0x96, 0xaf, 0x87, 0x91, 0xe3, 0xeb, 0x59, 0xbe, 0x3e, 0xfe, 0xdc, 0xf1,
	0xf5, 0x2d, 0xdf, 0x00, 0x6f, 0x3b, 0xbe, 0x81, 0xff, 0x7b, 0x0d, 0xb6, 0xc4, 0x81, 0xfa, 0xbf,
	0xe6, 0xff, 0x69, 0xcd, 0xf9, 0x4d, 0xc1, 0xd3, 0x6c, 0x57, 0xdd, 0x42, 0x1c, 0xbf, 0xae, 0xbc,
	0x85, 0x38, 0x7e, 0x5d, 0x7d, 0x0b, 0x71, 0xfc, 0xba, 0x03, 0x2c, 0xc4, 0xf1, 0xeb, 0x2e, 0xb0,
	0x10, 0xff, 0x05, 0x6c, 0xeb, 0xf7, 0x35, 0x62, 0x01, 0x19, 0x9f, 0x85, 0x79, 0x4c, 0x56, 0x5f,
	0x55, 0x61, 0x9a, 0xcd, 0x28, 0xd3, 0x7d, 0x20, 0xad, 0xee, 0xa7, 0x16, 0xd4, 0xf8, 0xf3, 0x8c,
	0x9e, 0x43, 0x43, 0x4a, 0x49, 0xf4, 0xc5, 0x9e, 0x25, 0xbf, 0xf7, 0xb4, 0xbe, 0x7c, 0x70, 0xdf,
	0x81, 0x8d, 0x18, 0xf6, 0x3f, 0x43, 0xdf, 0x42, 0x5d, 0x48, 0x18, 0xb4, 0xed, 0x4c, 0x51, 0x32,
	0xaf, 0xe4, 0xc3, 0xa1, 0x56, 0x24, 0x5a, 0x85, 0xa1, 0xaf, 0x9c, 0xb9, 0xcb, 0x12, 0xed, 0x26,
	0xa1, 0xb4, 0x98, 0xba, 0x32, 0xd4, 0x42, 0x69, 0x95, 0x84, 0x7a, 0x09, 0xeb, 0xb6, 0x4e, 0x42,
	0x0f, 0xaf, 0x08, 0xa4, 0x25, 0x54, 0x49, 0x98, 0xef, 0xa1, 0x65, 0x7e, 0xb7, 0x20, 0xec, 0x4c,
	0xb3, 0x7e, 0xcf, 0x94, 0x04, 0xf8, 0x19, 0xd0, 0x65, 0x05, 0x85, 0x9e, 0x3a, 0xf3, 0xaf, 0x92,
	0x58, 0xe5, 0x9c, 0x8c, 0xd0, 0x5a, 0xe2, 0x64, 0x09, 0xb0, 0x92, 0x00, 0xcf, 0xa1, 0x31, 0x62,
	0x39, 0x09, 0x53, 0x74, 0xcf, 0x99, 0xf3, 0xbe, 0xf4, 0xb3, 0x5d, 0xef, 0x99, 0x87, 0xbe, 0x83,
	0xf5, 0x11, 0xc9, 0xcf, 0x49, 0x7e, 0x87, 0x00, 0xcf, 0x3c, 0x5e, 0x15, 0x5b, 0x14, 0x2e, 0x55,
	0xc5, 0xd5, 0x8b, 0x25, 0x1b, 0x78, 0x05, 0x1b, 0xce, 0xe3, 0x8e, 0x1e, 0xb9, 0xd5, 0x75, 0x45,
	0x66, 0x79, 0x2a, 0x8d, 0xc8, 0x5a, 0x4a, 0xa5, 0x25, 0xbe, 0x4a, 0x02, 0x1c, 0x42, 0x67, 0x59,
	0x66, 0xa0, 0x27, 0xab, 0xc9, 0x08, 0x15, 0x72, 0xed, 0xc6, 0x16, 0x3a, 0xe0, 0xf2, 0xc6, 0x6c,
	0x8d, 0x50, 0x1e, 0xc8, 0x79, 0x5c, 0x96, 0x02, 0x2d, 0x3d, 0x3c, 0xe5, 0xfd, 0x7b, 0xf9, 0x7a,
	0x5a, 0xea, 0xdf, 0xab, 0xee, 0xaf, 0xd5, 0x21, 0x4f, 0x1a, 0xe2, 0xff, 0x81, 0xde, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0xb9, 0x4b, 0x9a, 0x2d, 0x10, 0x00, 0x00,
}
