# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

services:

  info-service:
    build: service/info-service
    command: --registry_address=consul:8500
    ports:
      - 50003:50051
    environment:
      NET: "host"
      DB_NAME: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "123456"
    depends_on:
      - mysql
      - consul

  user-service:
    build: service/user-service
    command: --registry_address=consul:8500
    ports:
      - 50004:50051
    environment:
      NET: "host"
      DB_NAME: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "123456"
    depends_on:
      - mysql
      - consul

  home-service:
    build: ./service/home-service
    command: --registry_address=consul:8500
    ports:
      - 50001:50051
    environment:
      NET: "host"
      DB_NAME: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "123456"
      REDIS_ADDR: "redis:6379"
      REDIS_PWD: ""
    depends_on:
      - mysql
      - consul
      - redis

  api-gateway:
    build: ./api-gateway
    command: --registry_address=consul:8500
    ports:
      - 8090:20050
    environment:
      NET: "host"
    depends_on:
      - consul

  consul:
    image: progrium/consul:latest
    container_name: consul-shop
    environment:
      NET: "host"
    command: -ui-dir /ui -server -bootstrap
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 5s
      timeout: 5s
      retries: 3

  database:
    image: postgres
    ports:
      - 5432:5432

  mysql:
    image: cytopia/mysql-8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - 3306:3306

  redis:
    image: redis
    environment:
      requirepass: "123456"
    ports:
      - 6379:6379

  datastore:
    image: mongo
    ports:
      - 27017:27017