// Code generated by protoc-gen-go. DO NOT EDIT.
// source: branch.proto

package ds_srv_branch

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errex if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelectBranchRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum              int32    `protobuf:"varint,2,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Latitude             string   `protobuf:"bytes,4,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,5,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	GeoHashCode          string   `protobuf:"bytes,6,opt,name=GeoHashCode,proto3" json:"GeoHashCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectBranchRequest) Reset()         { *m = SelectBranchRequest{} }
func (m *SelectBranchRequest) String() string { return proto.CompactTextString(m) }
func (*SelectBranchRequest) ProtoMessage()    {}
func (*SelectBranchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{0}
}

func (m *SelectBranchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectBranchRequest.Unmarshal(m, b)
}
func (m *SelectBranchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectBranchRequest.Marshal(b, m, deterministic)
}
func (m *SelectBranchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectBranchRequest.Merge(m, src)
}
func (m *SelectBranchRequest) XXX_Size() int {
	return xxx_messageInfo_SelectBranchRequest.Size(m)
}
func (m *SelectBranchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectBranchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectBranchRequest proto.InternalMessageInfo

func (m *SelectBranchRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SelectBranchRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *SelectBranchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SelectBranchRequest) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *SelectBranchRequest) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *SelectBranchRequest) GetGeoHashCode() string {
	if m != nil {
		return m.GeoHashCode
	}
	return ""
}

type SelectBranchDynamicsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	PageNum              int32    `protobuf:"varint,2,opt,name=PageNum,proto3" json:"PageNum,omitempty"`
	BranchID             int64    `protobuf:"varint,3,opt,name=BranchID,proto3" json:"BranchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectBranchDynamicsRequest) Reset()         { *m = SelectBranchDynamicsRequest{} }
func (m *SelectBranchDynamicsRequest) String() string { return proto.CompactTextString(m) }
func (*SelectBranchDynamicsRequest) ProtoMessage()    {}
func (*SelectBranchDynamicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{1}
}

func (m *SelectBranchDynamicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectBranchDynamicsRequest.Unmarshal(m, b)
}
func (m *SelectBranchDynamicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectBranchDynamicsRequest.Marshal(b, m, deterministic)
}
func (m *SelectBranchDynamicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectBranchDynamicsRequest.Merge(m, src)
}
func (m *SelectBranchDynamicsRequest) XXX_Size() int {
	return xxx_messageInfo_SelectBranchDynamicsRequest.Size(m)
}
func (m *SelectBranchDynamicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectBranchDynamicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectBranchDynamicsRequest proto.InternalMessageInfo

func (m *SelectBranchDynamicsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SelectBranchDynamicsRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *SelectBranchDynamicsRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

type Response struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type IdRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{4}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type BranchRespone struct {
	Results              string   `protobuf:"bytes,1,opt,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchRespone) Reset()         { *m = BranchRespone{} }
func (m *BranchRespone) String() string { return proto.CompactTextString(m) }
func (*BranchRespone) ProtoMessage()    {}
func (*BranchRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{5}
}

func (m *BranchRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchRespone.Unmarshal(m, b)
}
func (m *BranchRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchRespone.Marshal(b, m, deterministic)
}
func (m *BranchRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchRespone.Merge(m, src)
}
func (m *BranchRespone) XXX_Size() int {
	return xxx_messageInfo_BranchRespone.Size(m)
}
func (m *BranchRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchRespone.DiscardUnknown(m)
}

var xxx_messageInfo_BranchRespone proto.InternalMessageInfo

func (m *BranchRespone) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

type UrlRequest struct {
	BranchDynamicID      int64    `protobuf:"varint,1,opt,name=BranchDynamicID,proto3" json:"BranchDynamicID,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlRequest) Reset()         { *m = UrlRequest{} }
func (m *UrlRequest) String() string { return proto.CompactTextString(m) }
func (*UrlRequest) ProtoMessage()    {}
func (*UrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{6}
}

func (m *UrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlRequest.Unmarshal(m, b)
}
func (m *UrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlRequest.Marshal(b, m, deterministic)
}
func (m *UrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlRequest.Merge(m, src)
}
func (m *UrlRequest) XXX_Size() int {
	return xxx_messageInfo_UrlRequest.Size(m)
}
func (m *UrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UrlRequest proto.InternalMessageInfo

func (m *UrlRequest) GetBranchDynamicID() int64 {
	if m != nil {
		return m.BranchDynamicID
	}
	return 0
}

func (m *UrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateBranchDynamicRequest struct {
	BranchID             int64    `protobuf:"varint,1,opt,name=BranchID,proto3" json:"BranchID,omitempty"`
	BranchDynamicID      int64    `protobuf:"varint,2,opt,name=BranchDynamicID,proto3" json:"BranchDynamicID,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBranchDynamicRequest) Reset()         { *m = CreateBranchDynamicRequest{} }
func (m *CreateBranchDynamicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBranchDynamicRequest) ProtoMessage()    {}
func (*CreateBranchDynamicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{7}
}

func (m *CreateBranchDynamicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBranchDynamicRequest.Unmarshal(m, b)
}
func (m *CreateBranchDynamicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBranchDynamicRequest.Marshal(b, m, deterministic)
}
func (m *CreateBranchDynamicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBranchDynamicRequest.Merge(m, src)
}
func (m *CreateBranchDynamicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBranchDynamicRequest.Size(m)
}
func (m *CreateBranchDynamicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBranchDynamicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBranchDynamicRequest proto.InternalMessageInfo

func (m *CreateBranchDynamicRequest) GetBranchID() int64 {
	if m != nil {
		return m.BranchID
	}
	return 0
}

func (m *CreateBranchDynamicRequest) GetBranchDynamicID() int64 {
	if m != nil {
		return m.BranchDynamicID
	}
	return 0
}

func (m *CreateBranchDynamicRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateBranchDynamicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBranchDynamicRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type IdResponse struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResponse) Reset()         { *m = IdResponse{} }
func (m *IdResponse) String() string { return proto.CompactTextString(m) }
func (*IdResponse) ProtoMessage()    {}
func (*IdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{8}
}

func (m *IdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResponse.Unmarshal(m, b)
}
func (m *IdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResponse.Marshal(b, m, deterministic)
}
func (m *IdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResponse.Merge(m, src)
}
func (m *IdResponse) XXX_Size() int {
	return xxx_messageInfo_IdResponse.Size(m)
}
func (m *IdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IdResponse proto.InternalMessageInfo

func (m *IdResponse) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type AddResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20ce1f5884b7e047, []int{9}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*SelectBranchRequest)(nil), "ds.srv.branch.selectBranchRequest")
	proto.RegisterType((*SelectBranchDynamicsRequest)(nil), "ds.srv.branch.selectBranchDynamicsRequest")
	proto.RegisterType((*Response)(nil), "ds.srv.branch.response")
	proto.RegisterType((*CreateRequest)(nil), "ds.srv.branch.createRequest")
	proto.RegisterType((*IdRequest)(nil), "ds.srv.branch.idRequest")
	proto.RegisterType((*BranchRespone)(nil), "ds.srv.branch.BranchRespone")
	proto.RegisterType((*UrlRequest)(nil), "ds.srv.branch.urlRequest")
	proto.RegisterType((*CreateBranchDynamicRequest)(nil), "ds.srv.branch.createBranchDynamicRequest")
	proto.RegisterType((*IdResponse)(nil), "ds.srv.branch.idResponse")
	proto.RegisterType((*AddResponse)(nil), "ds.srv.branch.addResponse")
}

func init() { proto.RegisterFile("branch.proto", fileDescriptor_20ce1f5884b7e047) }

var fileDescriptor_20ce1f5884b7e047 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0xef, 0x69, 0x42, 0xd1, 0x36, 0x12, 0xae, 0x9b, 0x43, 0xb4, 0x1c, 0x48, 0x39,
	0xf8, 0x00, 0xbc, 0x00, 0xb5, 0xa5, 0x34, 0xa2, 0x54, 0xc8, 0x81, 0x13, 0xe2, 0xb0, 0x8d, 0x47,
	0xad, 0x25, 0xc7, 0x2e, 0xde, 0x35, 0x52, 0x79, 0x20, 0x5e, 0x82, 0x2b, 0x0f, 0x86, 0xbc, 0xf6,
	0x6e, 0x6c, 0x63, 0x7c, 0x80, 0xdb, 0xce, 0x7c, 0xe3, 0x6f, 0xbf, 0x9d, 0xf9, 0x3c, 0x30, 0xbd,
	0x4d, 0x59, 0xbc, 0xbb, 0x77, 0x1e, 0xd2, 0x44, 0x24, 0x64, 0x16, 0x70, 0x87, 0xa7, 0xdf, 0x9c,
	0x22, 0x49, 0x7f, 0x1a, 0x70, 0xca, 0x31, 0xc2, 0x9d, 0xb8, 0x94, 0x09, 0x1f, 0xbf, 0x66, 0xc8,
	0x05, 0xb1, 0x61, 0xf2, 0x81, 0xdd, 0xe1, 0x36, 0xfc, 0x8e, 0x96, 0xb1, 0x34, 0x56, 0x43, 0x5f,
	0xc7, 0xc4, 0x82, 0x71, 0x7e, 0xbe, 0xc9, 0xf6, 0x56, 0x4f, 0x42, 0x2a, 0x24, 0x04, 0x06, 0x37,
	0x6c, 0x8f, 0x56, 0x7f, 0x69, 0xac, 0x4c, 0x5f, 0x9e, 0x73, 0xa6, 0x6b, 0x26, 0x42, 0x91, 0x05,
	0x68, 0x0d, 0x64, 0x5e, 0xc7, 0x64, 0x01, 0xe6, 0x75, 0x12, 0xdf, 0x15, 0xe0, 0x50, 0x82, 0x87,
	0x04, 0x59, 0xc2, 0xf1, 0x1a, 0x93, 0x2b, 0xc6, 0xef, 0xdd, 0x24, 0x40, 0x6b, 0x24, 0xf1, 0x6a,
	0x8a, 0x26, 0x70, 0x5e, 0x15, 0xef, 0x3d, 0xc6, 0x6c, 0x1f, 0xee, 0xf8, 0xff, 0x3d, 0xc2, 0x86,
	0x49, 0x41, 0xb7, 0xf1, 0xe4, 0x43, 0xfa, 0xbe, 0x8e, 0xe9, 0x1b, 0x98, 0xa4, 0xc8, 0x1f, 0x92,
	0x98, 0x63, 0xfe, 0xd8, 0x80, 0x09, 0x26, 0x99, 0xa7, 0xbe, 0x3c, 0x93, 0x39, 0x0c, 0xdd, 0x24,
	0x8b, 0x45, 0xc9, 0x59, 0x04, 0xf4, 0x39, 0xcc, 0x76, 0x29, 0x32, 0x81, 0x4a, 0x58, 0xcb, 0xa7,
	0xf4, 0x1c, 0xcc, 0x30, 0x50, 0x05, 0x4f, 0xa0, 0xb7, 0xf1, 0x24, 0xdc, 0xf7, 0x7b, 0x1b, 0x8f,
	0x5e, 0xc0, 0x4c, 0xcd, 0x27, 0xbf, 0x5d, 0xca, 0xf7, 0x91, 0x67, 0x91, 0xe0, 0xb2, 0xca, 0xf4,
	0x55, 0x48, 0xaf, 0x00, 0xb2, 0x34, 0x52, 0x44, 0x2b, 0x38, 0xa9, 0xf5, 0x46, 0xb3, 0x36, 0xd3,
	0xe4, 0x29, 0xf4, 0xb3, 0x34, 0x92, 0xc2, 0x4d, 0x3f, 0x3f, 0xd2, 0x1f, 0x06, 0xd8, 0x85, 0xee,
	0x5a, 0x6d, 0xa5, 0xbb, 0xba, 0x4f, 0x46, 0xbd, 0x4f, 0x6d, 0xd7, 0xf6, 0xda, 0xaf, 0x9d, 0xc3,
	0xf0, 0x63, 0x28, 0x22, 0xe5, 0x99, 0x22, 0xd0, 0x46, 0x1a, 0x54, 0x8c, 0x64, 0xc1, 0xd8, 0x4d,
	0x62, 0x81, 0xb1, 0x28, 0xad, 0xa2, 0x42, 0xba, 0x00, 0xc8, 0x5b, 0x57, 0xce, 0xa5, 0xd9, 0xbb,
	0x17, 0x70, 0xcc, 0x82, 0x03, 0x6c, 0xc1, 0xf8, 0x6d, 0x10, 0xa4, 0xc8, 0x75, 0xe7, 0xca, 0xf0,
	0xd5, 0xaf, 0x21, 0x8c, 0x0a, 0x79, 0xc4, 0x83, 0xd9, 0x1a, 0x4b, 0x57, 0x5d, 0x3e, 0x6e, 0x3c,
	0x62, 0x39, 0xb5, 0xff, 0xc6, 0xd1, 0xa3, 0xb2, 0x9f, 0x35, 0x10, 0xe5, 0x0f, 0x7a, 0x44, 0xde,
	0xc1, 0x5c, 0xb3, 0x94, 0x2f, 0xfe, 0x77, 0xb2, 0xf7, 0x30, 0xdd, 0x56, 0xbc, 0x4e, 0x68, 0xa3,
	0xb4, 0xe5, 0x2f, 0xee, 0xa2, 0x5b, 0xc3, 0xd4, 0xad, 0xcc, 0x96, 0x2c, 0x1a, 0xa5, 0x35, 0xc3,
	0x76, 0x11, 0x7d, 0x86, 0x53, 0xf7, 0x4f, 0x93, 0x90, 0x8b, 0x56, 0xbe, 0x36, 0x23, 0x75, 0xab,
	0x3c, 0xa9, 0x92, 0x7f, 0x4a, 0x23, 0x72, 0xd6, 0xa8, 0x3e, 0x98, 0xbd, 0x8b, 0xc8, 0xcb, 0x77,
	0x89, 0xd0, 0xfe, 0xfc, 0xfb, 0x04, 0xce, 0x5a, 0x10, 0xcd, 0xf2, 0x05, 0xe6, 0xdb, 0x96, 0x7d,
	0x43, 0x5e, 0x76, 0xcc, 0xa2, 0xb1, 0x94, 0xba, 0x45, 0xc2, 0x1a, 0x45, 0x69, 0xc7, 0x0e, 0x8d,
	0x76, 0x03, 0xa9, 0xd8, 0x9b, 0x1e, 0xdd, 0x8e, 0xe4, 0xa2, 0x7f, 0xfd, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x2f, 0x6b, 0x34, 0xf8, 0x05, 0x00, 0x00,
}
