// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package ds_srv_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errex if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*******************************
type VfCodeIn struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VfCodeIn) Reset()         { *m = VfCodeIn{} }
func (m *VfCodeIn) String() string { return proto.CompactTextString(m) }
func (*VfCodeIn) ProtoMessage()    {}
func (*VfCodeIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *VfCodeIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VfCodeIn.Unmarshal(m, b)
}
func (m *VfCodeIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VfCodeIn.Marshal(b, m, deterministic)
}
func (m *VfCodeIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VfCodeIn.Merge(m, src)
}
func (m *VfCodeIn) XXX_Size() int {
	return xxx_messageInfo_VfCodeIn.Size(m)
}
func (m *VfCodeIn) XXX_DiscardUnknown() {
	xxx_messageInfo_VfCodeIn.DiscardUnknown(m)
}

var xxx_messageInfo_VfCodeIn proto.InternalMessageInfo

func (m *VfCodeIn) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

//*******************************
type CommonOut struct {
	Httpcode             int32    `protobuf:"varint,1,opt,name=httpcode,proto3" json:"httpcode,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Innermsg             string   `protobuf:"bytes,4,opt,name=innermsg,proto3" json:"innermsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonOut) Reset()         { *m = CommonOut{} }
func (m *CommonOut) String() string { return proto.CompactTextString(m) }
func (*CommonOut) ProtoMessage()    {}
func (*CommonOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *CommonOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonOut.Unmarshal(m, b)
}
func (m *CommonOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonOut.Marshal(b, m, deterministic)
}
func (m *CommonOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonOut.Merge(m, src)
}
func (m *CommonOut) XXX_Size() int {
	return xxx_messageInfo_CommonOut.Size(m)
}
func (m *CommonOut) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonOut.DiscardUnknown(m)
}

var xxx_messageInfo_CommonOut proto.InternalMessageInfo

func (m *CommonOut) GetHttpcode() int32 {
	if m != nil {
		return m.Httpcode
	}
	return 0
}

func (m *CommonOut) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonOut) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CommonOut) GetInnermsg() string {
	if m != nil {
		return m.Innermsg
	}
	return ""
}

func (m *CommonOut) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*VfCodeIn)(nil), "ds.srv.base.VfCodeIn")
	proto.RegisterType((*CommonOut)(nil), "ds.srv.base.CommonOut")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x29, 0xd6, 0x2b, 0x2e, 0x2a, 0xd3, 0x03,
	0x09, 0x29, 0x29, 0x71, 0x71, 0x84, 0xa5, 0x39, 0xe7, 0xa7, 0xa4, 0x7a, 0xe6, 0x09, 0x89, 0x71,
	0xb1, 0xe5, 0xe6, 0x27, 0x65, 0xe6, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79,
	0x4a, 0xb5, 0x5c, 0x9c, 0xce, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0xfe, 0xa5, 0x25, 0x42, 0x52, 0x5c,
	0x1c, 0x19, 0x25, 0x25, 0x05, 0xc9, 0xf9, 0x29, 0x10, 0x65, 0xac, 0x41, 0x70, 0xbe, 0x90, 0x10,
	0x17, 0x0b, 0x58, 0x9c, 0x09, 0x2c, 0x0e, 0x66, 0x0b, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x4b,
	0x30, 0x83, 0x4d, 0x04, 0x31, 0x41, 0x26, 0x64, 0xe6, 0xe5, 0xa5, 0x16, 0x81, 0x84, 0x59, 0xc0,
	0xc2, 0x70, 0x3e, 0xc8, 0x84, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x56, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x30, 0xdb, 0xc8, 0x91, 0x8b, 0xc5, 0x29, 0xb1, 0x38, 0x55, 0xc8, 0x92, 0x8b, 0x0d, 0xe2, 0x54,
	0x21, 0x51, 0x3d, 0x24, 0x2f, 0xe8, 0xc1, 0xdc, 0x2f, 0x25, 0x86, 0x22, 0x0c, 0x77, 0xb2, 0x12,
	0x43, 0x12, 0x1b, 0xd8, 0xe7, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xb2, 0x96, 0xa1,
	0x07, 0x01, 0x00, 0x00,
}
